package com.example.ui.localization

import java.util.Locale

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिन्दी (Hindi)"),
    BENGALI("bn", "বাংলা (Bengali)"),
    TAMIL("ta", "தமிழ் (Tamil)"),
    TELUGU("te", "తెలుగు (Telugu)"),
    ARABIC("ar", "العربية (Arabic)"),
    URDU("ur", "اردو (Urdu)"),
    MARATHI("mr", "मराठी (Marathi)"),
    GUJARATI("gu", "ગુજરાતી (Gujarati)"),
    PUNJABI("pa", "ਪੰਜਾਬੀ (Punjabi)"),
    MALAYALAM("ml", "മലയാളം (Malayalam)")
}

object JobaayaLocalization {
    
    fun detectDeviceLanguage(): AppLanguage {
        val defaultLang = Locale.getDefault().language
        return AppLanguage.entries.find { it.code == defaultLang } ?: AppLanguage.ENGLISH
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_tagline" to "Professional Networking & Business Growth",
            "search_placeholder" to "Search profession, skill, location...",
            "near_me" to "Near Me",
            "chats" to "Chats",
            "notes" to "My Notes",
            "settings" to "Settings",
            "admin_panel" to "Admin Panel",
            "calculator" to "Calculator",
            "bookmarks" to "Bookmarks",
            "login_title" to "Welcome",
            "login_subtitle" to " ",
            "otp_login" to "OTP Mobile Login",
            "email_login" to "Email Login",
            "google_signin" to "Google Sign-In",
            "enter_mobile" to "Enter Mobile Number",
            "enter_otp" to "Enter 6-Digit OTP",
            "send_otp" to "Send Verification Code",
            "verify_otp" to "Verify & Proceed",
            "enter_email" to "Enter Email Address",
            "enter_password" to "Enter Password",
            "login" to "Login",
            "logout" to "Log Out",
            "register" to "Complete Registration",
            "select_account_type" to "Select Your Account Type",
            "customer" to "Customer",
            "professional" to "Professional",
            "business" to "Business",
            "full_name" to "Full Name",
            "profession" to "Profession (e.g. Electrician, Lawyer)",
            "skills" to "Skills (comma separated)",
            "mobile_number" to "Mobile Number",
            "email" to "Email Address",
            "address" to "Full Address / Location text",
            "experience" to "Years of Experience",
            "languages" to "Languages Spoken (comma separated)",
            "about" to "About / Working details (Free Text)",
            "save_profile" to "Save Professional Profile",
            "hire_me" to "Hire Me",
            "hire_now" to "Send Hiring Enquiry",
            "call" to "Call Now",
            "whatsapp" to "WhatsApp Chat",
            "profile_views" to "Profile Views",
            "interactions" to "Interactions",
            "reviews" to "Customer Reviews",
            "write_review" to "Write a Review",
            "submit_review" to "Submit Star Rating",
            "report" to "Report Profile",
            "block" to "Block User",
            "sp_block_success" to "User blocked successfully.",
            "sp_report_success" to "Profile reported to moderators.",
            "status_available" to "Available for Work",
            "status_busy" to "Currently Busy",
            "status_offline" to "Offline",
            "working_hours" to "Working Hours",
            "avail_title" to "My Work Availability",
            "notifications" to "Activity Alerts",
            "notification_settings" to "Push Notifications Toggle",
            "gps_locate" to "Enable Public GPS Sharing",
            "directions" to "Get Route Directions",
            "share_profile" to "Share Profile",
            "qr_share" to "Profile QR Code Scanner",
            "verified" to "Verified Professional",
            "badge" to "Grant Verification Badge",
            "admin_users" to "Accounts Manager",
            "admin_reports" to "Moderation Audit Logs",
            "admin_analytics" to "Growth Insights Dashboard",
            "create_note" to "Create Note",
            "note_title" to "Title",
            "note_body" to "Write something...",
            "delete" to "Delete",
            "calc_title" to "Service Calculator",
            "calc_hint" to "Calculate rates, & quotations",
            "currency_counter" to "Cash Counter",
            "hiring_success" to "Congratulation! Your hiring enquiry has been dispatched locally.",
            "unlimited_msg" to "Enter any custom trade. Supports electrician, mechanic, doctor, consultant, or any future profession.",
            "no_results" to "No professionals match your filters. Try search keywords!",
            "set_photo" to "Set Profile Photo",
            "adjust_photo" to "Adjust Photo",
            "save_photo" to "Save Photo",
            "cancel" to "Cancel",
            "zoom_to_fit" to "Zoom to Fit",
            "new_to_app" to "New to jobaaya?",
            "filters" to "Filters",
            "refine_search" to "Refine Network Search",
            "connect" to "Connect",
            "connected" to "Connected"
        ),
        AppLanguage.HINDI to mapOf(
            "app_tagline" to "पेशेवर नेटवर्किंग और व्यावसायिक विकास",
            "search_placeholder" to "पेशा, कौशल, या स्थान खोजें...",
            "near_me" to "मेरे पास",
            "chats" to "बातचीत (Chats)",
            "notes" to "मेरी टिप्पणियाँ",
            "settings" to "सेटिंग्स",
            "admin_panel" to "एडमिन पैनल",
            "calculator" to "कैलकुलेटर",
            "bookmarks" to "बुकमार्क",
            "login_title" to "jobaaya में आपका स्वागत है",
            "login_subtitle" to "पेशेवर विकास और नेटवर्किंग मंच",
            "otp_login" to "ओटीपी मोबाइल लॉगिन",
            "email_login" to "ईमेल लॉगिन",
            "google_signin" to "गूगल साइन-इन",
            "enter_mobile" to "मोबाइल नंबर दर्ज करें",
            "enter_otp" to "6-अंकीय ओटीपी दर्ज करें",
            "send_otp" to "सत्यापन कोड भेजें",
            "verify_otp" to "सत्यापित करें और आगे बढ़ें",
            "enter_email" to "ईमेल पता दर्ज करें",
            "enter_password" to "पासवर्ड दर्ज करें",
            "login" to "लॉगिन करें",
            "logout" to "लॉग आउट",
            "register" to "पंजीकरण पूरा करें",
            "select_account_type" to "अपना खाता प्रकार चुनें",
            "customer" to "ग्राहक (Customer)",
            "professional" to "पेशेवर (Professional)",
            "business" to "व्यवसाय (Business)",
            "full_name" to "पूरा नाम",
            "profession" to "पेशा (जैसे प्लंबर, वकील, बिजली मिस्त्री)",
            "skills" to "कौशल (अल्पविराम से अलग)",
            "mobile_number" to "मोबाइल नंबर",
            "email" to "ईमेल पता",
            "address" to "पूरा पता / स्थान",
            "experience" to "अनुभव (वर्षों में)",
            "languages" to "बोली जाने वाली भाषाएं",
            "about" to "मेरे बारे में / काम का विवरण",
            "save_profile" to "प्रोफ़ाइल सहेजें",
            "hire_me" to "हायर करें (Hire)",
            "hire_now" to "पूछताछ भेजें",
            "call" to "कॉल करें",
            "whatsapp" to "व्हाट्सएप चैट",
            "profile_views" to "प्रोफ़ाइल व्यूज",
            "interactions" to "बातचीत / क्लिक",
            "reviews" to "ग्राहक समीक्षाएं",
            "write_review" to "समीक्षा लिखें",
            "submit_review" to "रेटिंग सबमिट करें",
            "report" to "रिपोर्ट करें",
            "block" to "ब्लॉक करें",
            "sp_block_success" to "उपयोगकर्ता को ब्लॉक कर दिया गया है।",
            "sp_report_success" to "प्रोफ़ाइल की रिपोर्ट एडमिन को की गई।",
            "status_available" to "काम के लिए उपलब्ध",
            "status_busy" to "अभी व्यस्त",
            "status_offline" to "ऑफ़लाइन",
            "working_hours" to "काम के घंटे",
            "avail_title" to "काम की उपलब्धता",
            "notifications" to "गतिविधि अलर्ट",
            "notification_settings" to "पुश नोटिफिकेशन सेटिंग्स",
            "gps_locate" to "सार्वजनिक जीपीएस स्थान दिखाना",
            "directions" to "मार्ग निर्देश",
            "share_profile" to "प्रोफ़ाइल साझा करें",
            "qr_share" to "प्रोफ़ाइल क्यूআর कोड",
            "verified" to "सत्यापित पेशेवर ⚡",
            "badge" to "सत्यापन बैज दें",
            "admin_users" to "खाता प्रबंधक",
            "admin_reports" to "रिपोर्ट और ब्लॉक ऑडिट",
            "admin_analytics" to "व्यावसायिक अंतर्दृष्टि",
            "create_note" to "क्रिएट नोट",
            "note_title" to "शीर्षक",
            "note_body" to "कुछ लिखें...",
            "delete" to "हटाएं",
            "calc_title" to "सेवा दर और कोटेशन कैलकुलेटर",
            "calc_hint" to "दर और कोटेशन की गणना करें",
            "currency_counter" to "キャッシュカウンター",
            "hiring_success" to "बधाई! आपकी पूछताछ स्थानीय स्तर पर भेज दी गई है।",
            "unlimited_msg" to "किसी भी पेशे को दर्ज करें। कोई प्रतिबंध नहीं है।",
            "no_results" to "कोई पेशेवर नहीं मिला। कृपया अन्य खोज शब्द आज़माएं।",
            "set_photo" to "प्रोफ़ाइल फोटो सेट करें",
            "adjust_photo" to "फोटो को सही करें",
            "save_photo" to "फोटो सहेजें",
            "cancel" to "रद्द करें",
            "zoom_to_fit" to "फिट करने के लिए ज़ूम करें",
            "new_to_app" to "jobaaya पर नए हैं?",
            "filters" to "फ़िल्टर",
            "refine_search" to "खोज को बेहतर बनाएं",
            "connect" to "जुड़ें",
            "connected" to "जुड़े हुए"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_tagline" to "পেশাদার নেটওয়ার্কিং এবং ব্যবসায়িক বৃদ্ধি",
            "search_placeholder" to "পেশা, দক্ষতা বা স্থান খুঁজুন...",
            "near_me" to "আমার কাছাকাছি",
            "chats" to "চ্যাট",
            "notes" to "আমার নোট",
            "settings" to "সেটিংস",
            "login" to "লগইন",
            "register" to "নিবন্ধন সম্পন্ন করুন",
            "hire_me" to "হায়ার করুন",
            "verified" to "যাচাইকৃত পেশাদার",
            "call" to "কল করুন",
            "whatsapp" to "হোয়াটসঅ্যাপ চ্যাট",
            "save_profile" to "প্রোফাইল সংরক্ষণ করুন"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_tagline" to "தொழில்முறை நெட்வொர்க்கிங் மற்றும் வணிக வளர்ச்சி",
            "search_placeholder" to "தொழில், திறன் அல்லது இடத்தைத் தேடுங்கள்...",
            "near_me" to "எனக்கு அருகில்",
            "chats" to "அரட்டைகள்",
            "notes" to "எனது குறிப்புகள்",
            "settings" to "அமைப்புகள்",
            "login" to "உள்நுழை",
            "register" to "பதிவை முடிக்கவும்",
            "hire_me" to "வேலைக்கு அமர்த்தவும்",
            "verified" to "சரிபார்க்கப்பட்ட நிபுணர்",
            "call" to "இப்போதே அழையுங்கள்",
            "whatsapp" to "வாட்ஸ்அப் அரட்டை",
            "save_profile" to "சுயவிவரத்தைச் சேமி"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_tagline" to "ప్రొఫెషనల్ నెట్‌వర్కింగ్ & వ్యాపార వృద్ధి",
            "search_placeholder" to "వృత్తి, నైపుణ్యం లేదా స్థానాన్ని వెతకండి...",
            "near_me" to "నా దగ్గరలో",
            "chats" to "చాట్‌లు",
            "notes" to "నా గమనికలు",
            "settings" to "సెట్టింగ్‌లు",
            "login" to "లాగిన్",
            "register" to "రిజిస్ట్రేషన్ పూర్తి చేయండి",
            "hire_me" to "హైర్ చేయండి",
            "verified" to "ధృవీకరించబడిన ప్రొఫెషనల్",
            "call" to "కాల్ చేయండి",
            "whatsapp" to "వాట్సాప్ చాట్",
            "save_profile" to "ప్రొఫైల్‌ను సేవ్ చేయండి"
        ),
        AppLanguage.ARABIC to mapOf(
            "app_tagline" to "التواصل المهني ونمو الأعمال",
            "search_placeholder" to "بحث عن مهنة، مهارة، موقع...",
            "near_me" to "بالقرب مني",
            "chats" to "المحادثات",
            "notes" to "ملاحظاتي",
            "settings" to "الإعدادات",
            "login" to "تسجيل الدخول",
            "register" to "إكمال التسجيل",
            "hire_me" to "وظفني",
            "verified" to "محترف موثق",
            "call" to "اتصل الآن",
            "whatsapp" to "دردشة واتساب",
            "save_profile" to "حفظ الملف الشخصي"
        ),
        AppLanguage.URDU to mapOf(
            "app_tagline" to "پیشہ ورانہ نیٹ ورکنگ اور کاروباری ترقی",
            "search_placeholder" to "پیشہ، مہارت یا جگہ تلاش کریں...",
            "near_me" to "میرے قریب",
            "chats" to "بات چیت",
            "notes" to "میرے نوٹس",
            "settings" to "ترتیبات",
            "login" to "لاگ ان",
            "register" to "رجسٹریشن مکمل کریں",
            "hire_me" to "ہائر کریں",
            "verified" to "تصدیق شدہ پیشہ ور",
            "call" to "ابھی کال کریں",
            "whatsapp" to "واٹس ایپ چیٹ",
            "save_profile" to "پروفائل محفوظ کریں"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_tagline" to "व्यावसायिक नेटवर्किंग आणि व्यवसाय वाढ",
            "search_placeholder" to "व्यवसाय, कौशल्य किंवा ठिकाण शोधा...",
            "near_me" to "माझ्या जवळ",
            "chats" to "चॅट्स",
            "notes" to "माझ्या नोट्स",
            "settings" to "सेटिंग्ज",
            "login" to "লগইন",
            "register" to "नोंदणी पूर्ण करा",
            "hire_me" to "हायर करा",
            "verified" to "सत्यापित व्यावसायिक",
            "call" to "कॉल करा",
            "whatsapp" to "व्हॉट्सॲप चॅट",
            "save_profile" to "प्रोफाइल जतन करा"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_tagline" to "વ્યાવસાયિક નેટવર્કિંગ અને વ્યવસાય વૃદ્ધિ",
            "search_placeholder" to "વ્યવસાય, કૌશલ્ય અથવા સ્થળ શોધો...",
            "near_me" to "મારી નજીક",
            "chats" to "ચેટ્સ",
            "notes" to "મારી નોંધો",
            "settings" to "સેટિંગ્સ",
            "login" to "લોગિન",
            "register" to "નોંધણી પૂર્ણ કરો",
            "hire_me" to "હાયર કરો",
            "verified" to "ચકાસાયેલ વ્યાવસાયિક",
            "call" to "કોલ કરો",
            "whatsapp" to "વોટ્સએપ ચેટ",
            "save_profile" to "પ્રોફાઇલ સાચવો"
        ),
        AppLanguage.PUNJABI to mapOf(
            "app_tagline" to "ਪੇਸ਼ੇਵਰ ਨੈੱਟਵਰਕਿੰਗ ਅਤੇ ਕਾਰੋਬਾਰੀ ਵਿਕਾਸ",
            "search_placeholder" to "ਪੇਸ਼ਾ, ਹੁਨਰ ਜਾਂ ਸਥਾਨ ਲੱਭੋ...",
            "near_me" to "ਮੇਰੇ ਨੇੜੇ",
            "chats" to "ਚੈਟਸ",
            "notes" to "ਮੇਰੇ ਨੋਟਸ",
            "settings" to "ਸੈਟਿੰਗਾਂ",
            "login" to "ਲੌਗਇਨ",
            "register" to "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰੋ",
            "hire_me" to "ਹਾਇਰ ਕਰੋ",
            "verified" to "ਤਸਦੀਕ ਪੇਸ਼ੇਵਰ",
            "call" to "ਕਾਲ ਕਰੋ",
            "whatsapp" to "ਵਟਸਐਪ ਚੈਟ",
            "save_profile" to "ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕਰੋ"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_tagline" to "പ്രൊഫഷണൽ നെറ്റ്വർക്കിംഗും ബിസിനസ്സ് വളർച്ചയും",
            "search_placeholder" to "തൊഴിൽ, വൈദഗ്ധ്യം അല്ലെങ്കിൽ സ്ഥലം തിരയുക...",
            "near_me" to "എന്റെ അടുത്ത്",
            "chats" to "ചാറ്റുകൾ",
            "notes" to "എന്റെ കുറിപ്പുകൾ",
            "settings" to "ക്രമീകരണങ്ങൾ",
            "login" to "ലോഗിൻ",
            "register" to "രജിസ്ട്രേഷൻ പൂർത്തിയാക്കുക",
            "hire_me" to "ഹയർ ചെയ്യുക",
            "verified" to "സ്ഥിരീകരിച്ച പ്രൊഫഷണൽ",
            "call" to "ഇപ്പോൾ വിളിക്കുക",
            "whatsapp" to "വാട്ട്‌സ്ആപ്പ് ചാറ്റ്",
            "save_profile" to "പ്രൊഫൈൽ സംരക്ഷിക്കുക"
        )
    )

    fun translate(key: String, language: AppLanguage): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }
}
