package com.example.ui.localization

import java.util.Locale

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिन्दी (Hindi)"),
    BENGALI("bn", "বাংলা (Bengali)"),
    TAMIL("ta", "தமிழ் (Tamil)"),
    TELUGU("te", "తెలుగు (Telugu)"),
    ARABIC("ar", "العربية (Arabic)"),
    URDU("ur", "اردو (Urdu)"),
    MARATHI("mr", "मराठी (Marathi)"),
    GUJARATI("gu", "ગુજરાતી (Gujarati)"),
    PUNJABI("pa", "ਪੰਜਾਬੀ (Punjabi)"),
    MALAYALAM("ml", "മലയാളം (Malayalam)")
}

object JobaayaLocalization {
    
    fun detectDeviceLanguage(): AppLanguage {
        val defaultLang = Locale.getDefault().language
        return AppLanguage.entries.find { it.code == defaultLang } ?: AppLanguage.ENGLISH
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_tagline" to "Professional Networking & Business Growth",
            "search_placeholder" to "Search profession, skill, location...",
            "near_me" to "Near Me",
            "chats" to "Chats",
            "notes" to "My Notes",
            "settings" to "Settings",
            "admin_panel" to "Admin Panel",
            "calculator" to "Calculator",
            "bookmarks" to "Bookmarks",
            "login_title" to "Welcome",
            "login_subtitle" to "Professional Networking & Business Growth",
            "otp_login" to "OTP Mobile Login",
            "email_login" to "Email Login",
            "google_signin" to "Google Sign-In",
            "enter_mobile" to "Enter Mobile Number",
            "enter_otp" to "Enter 6-Digit OTP",
            "send_otp" to "Send Verification Code",
            "resend_otp" to "Resend OTP",
            "verify_otp" to "Verify & Proceed",
            "enter_email" to "Enter Email Address",
            "enter_password" to "Enter Password",
            "login" to "Login",
            "logout" to "Log Out",
            "register" to "Complete Registration",
            "select_account_type" to "Select Your Account Type",
            "customer" to "Customer",
            "professional" to "Professional",
            "business" to "Business",
            "full_name" to "Full Name",
            "profession" to "Profession (e.g. Electrician, Lawyer)",
            "skills" to "Skills",
            "mobile_number" to "Mobile Number",
            "email" to "Email Address",
            "address" to "Full Address / Location text",
            "experience" to "Years of Experience",
            "languages" to "Language",
            "about" to "About / Working details (Free Text)",
            "save_profile" to "Save Professional Profile",
            "hire_me" to "Hire Me",
            "hire_now" to "Send Hiring Enquiry",
            "call" to "Call Now",
            "whatsapp" to "WhatsApp Chat",
            "profile_views" to "Profile Views",
            "interactions" to "Interactions",
            "reviews" to "Customer Reviews",
            "write_review" to "Write a Review",
            "submit_review" to "Submit Star Rating",
            "report" to "Report Profile",
            "block" to "Block User",
            "sp_block_success" to "User blocked successfully.",
            "sp_report_success" to "Profile reported to moderators.",
            "status_available" to "Available for Work",
            "status_busy" to "Currently Busy",
            "status_offline" to "Offline",
            "working_hours" to "Working Hours",
            "avail_title" to "My Work Availability",
            "notifications" to "Activity Alerts",
            "notification_settings" to "Push Notifications Toggle",
            "gps_locate" to "Enable Public GPS Sharing",
            "directions" to "Get Route",
            "share_profile" to "Share Profile",
            "qr_share" to "Profile QR Code Scanner",
            "verified" to "Verified Professional",
            "badge" to "Grant Verification Badge",
            "admin_users" to "Accounts Manager",
            "admin_reports" to "Moderation Audit Logs",
            "admin_analytics" to "Growth Insights Dashboard",
            "create_note" to "Create Note",
            "note_title" to "Title",
            "note_body" to "Write something...",
            "delete" to "Delete",
            "calc_title" to "Service Calculator",
            "calc_hint" to "Calculate rates, & quotations",
            "currency_counter" to "Cash Counter",
            "hiring_success" to "Congratulations! Your hiring enquiry has been dispatched locally.",
            "unlimited_msg" to "Enter any custom trade. Supports electrician, mechanic, doctor, consultant, or any future profession.",
            "no_results" to "No professionals match your filters. Try search keywords!",
            "set_photo" to "Set Profile Photo",
            "adjust_photo" to "Adjust Photo",
            "save_photo" to "Save Photo",
            "cancel" to "Cancel",
            "zoom_to_fit" to "Zoom to Fit",
            "new_to_app" to "New to jobaaya?",
            "filters" to "Filters",
            "refine_search" to "Refine Network Search",
            "connect" to "Connect",
            "connected" to "Connected",
            "select_language" to "Select Language",
            "all" to "All",
            "total_amount" to "Total Amount",
            "privacy_settings" to "Privacy Settings",
            "public_mobile" to "Public Mobile Number",
            "public_mobile_desc" to "Allow everyone to see your contact",
            "private_account" to "Private Account",
            "private_account_desc" to "Only connections can view full details",
            "blocked_list" to "Blocked Users List",
            "delete_account" to "Delete Account Permanently",
            "app_data" to "App & Data",
            "clear_cache" to "Clear Cache",
            "support_social" to "Support & Social",
            "help_center" to "Help Center / Contact Us",
            "report_bug" to "Report a Bug",
            "share_app" to "Share jobaaya App",
            "rate_us" to "Rate Us on Play Store",
            "unverified" to "Unverified",
            "verified_filter" to "Verified",
            "blocked_filter" to "Blocked",
            "home" to "Home",
            "tools" to "Tools",
            "profile" to "Profile",
            "activity_logs" to "Platform Activity Logs",
            "no_activity_logs" to "No recent activity logs",
            "my_profile_title" to "MY PROFESSIONAL PROFILE",
            "prof_details" to "Professional Details",
            "lang_sep" to "Language",
            "preview" to "Preview",
            "service_area" to "Service Area",
            "save_all" to "Save All Details",
            "saved_toast" to "Saved",
            "live_map_desc" to "Live Network Map - Find local experts nearby",
            "loc_req" to "Location Access Required",
            "loc_req_desc" to "Grant permission to see nearby tradespeople",
            "grant_perm" to "Grant Permission",
            "prof_proximity" to "Professionals in Your Proximity"
        ),
        AppLanguage.HINDI to mapOf(
            "app_tagline" to "पेशेवर नेटवर्किंग और व्यावसायिक विकास",
            "search_placeholder" to "पेशा, कौशल, या स्थान खोजें...",
            "near_me" to "मेरे पास",
            "chats" to "बातचीत",
            "notes" to "मेरी टिप्पणियाँ",
            "settings" to "सेटिंग्स",
            "admin_panel" to "एडमिन पैनल",
            "calculator" to "कैलकुलेटर",
            "bookmarks" to "बुकमार्क",
            "login_title" to "jobaaya में आपका स्वागत है",
            "login_subtitle" to "पेशेवर विकास और नेटवर्किंग मंच",
            "otp_login" to "ओटीपी मोबाइल लॉगिन",
            "email_login" to "ईमेल लॉगिन",
            "google_signin" to "गूगल साइन-इन",
            "enter_mobile" to "मोबाइल नंबर दर्ज करें",
            "enter_otp" to "6-अंकीय ओटीपी दर्ज करें",
            "send_otp" to "सत्यापन कोड भेजें",
            "resend_otp" to "ओटीपी पुन: भेजें",
            "verify_otp" to "सत्यापित करें और आगे बढ़ें",
            "enter_email" to "ईमेल पता दर्ज करें",
            "enter_password" to "पासवर्ड दर्ज करें",
            "login" to "लॉगिन करें",
            "logout" to "लॉग आउट",
            "register" to "पंजीकरण पूरा करें",
            "select_account_type" to "अपना खाता प्रकार चुनें",
            "customer" to "ग्राहक (Customer)",
            "professional" to "पेशेवर (Professional)",
            "business" to "व्यवसाय (Business)",
            "full_name" to "पूरा नाम",
            "profession" to "पेशा (जैसे प्लंबर, वकील, बिजली मिस्त्री)",
            "skills" to "कौशल",
            "mobile_number" to "मोबाइल नंबर",
            "email" to "ईमेल पता",
            "address" to "पूरा पता / स्थान",
            "experience" to "अनुभव (वर्षों में)",
            "languages" to "भाषा",
            "about" to "मेरे बारे में / काम का विवरण",
            "save_profile" to "प्रोफ़ाइल सहेजें",
            "hire_me" to "हायर करें (Hire)",
            "hire_now" to "पूछताछ भेजें",
            "call" to "कॉल करें",
            "whatsapp" to "व्हाट्सएप चैट",
            "profile_views" to "प्रोफ़ाइल व्यूज",
            "interactions" to "बातचीत / क्लिक",
            "reviews" to "ग्राहक समीक्षाएं",
            "write_review" to "समीक्षा लिखें",
            "submit_review" to "रेटिंग सबमिट करें",
            "report" to "रिपोर्ट करें",
            "block" to "ब्लॉक करें",
            "sp_block_success" to "उपयोगकर्ता को ब्लॉक कर दिया गया है।",
            "sp_report_success" to "प्रोफ़ाइल की रिपोर्ट एडमिन को की गई।",
            "status_available" to "काम के लिए उपलब्ध",
            "status_busy" to "अभी व्यस्त",
            "status_offline" to "ऑफ़लाइन",
            "working_hours" to "काम के घंटे",
            "avail_title" to "काम की उपलब्धता",
            "notifications" to "गतिविधि अलर्ट",
            "notification_settings" to "पुश नोटिफिकेशन सेटिंग्स",
            "gps_locate" to "सार्वजनिक जीपीएस स्थान दिखाना",
            "directions" to "मार्ग",
            "share_profile" to "प्रोफ़ाइल साझा करें",
            "qr_share" to "प्रोफ़ाइल क्यूআর कोड",
            "verified" to "सत्यापित पेशेवर ⚡",
            "badge" to "सत्यापन बैज दें",
            "admin_users" to "खाता प्रबंधक",
            "admin_reports" to "रिपोर्ट और ब्लॉक ऑडिट",
            "admin_analytics" to "व्यावसायिक अंतर्दृष्टि",
            "create_note" to "क्रिएट नोट",
            "note_title" to "शीर्षक",
            "note_body" to "कुछ लिखें...",
            "delete" to "हटाएं",
            "calc_title" to "सेवा दर और कोटेशन कैलकुलेटर",
            "calc_hint" to "दर और कोटेशन की गणना करें",
            "currency_counter" to "कैश काउंटर",
            "hiring_success" to "बधाई! आपकी पूछताछ स्थानीय स्तर पर भेज दी गई है।",
            "unlimited_msg" to "किसी भी पेशे को दर्ज करें। कोई प्रतिबंध नहीं है।",
            "no_results" to "कोई पेशेवर नहीं मिला। कृपया अन्य खोज शब्द आज़माएं।",
            "set_photo" to "प्रोफ़ाइल फोटो सेट करें",
            "adjust_photo" to "फोटो को सही करें",
            "save_photo" to "फोटो सहेजें",
            "cancel" to "रद्द करें",
            "zoom_to_fit" to "फिट करने के लिए ज़ूम करें",
            "new_to_app" to "jobaaya पर नए हैं?",
            "filters" to "फ़िल्टर",
            "refine_search" to "खोज को बेहतर बनाएं",
            "connect" to "जुड़ें",
            "connected" to "जुड़े हुए",
            "select_language" to "भाषा चुनें",
            "all" to "सभी",
            "total_amount" to "कुल राशि",
            "privacy_settings" to "गोपनीयता सेटिंग्स",
            "public_mobile" to "सार्वजनिक मोबाइल नंबर",
            "public_mobile_desc" to "सभी को अपना संपर्क देखने दें",
            "private_account" to "निजी खाता",
            "private_account_desc" to "केवल कनेक्शन ही पूर्ण विवरण देख सकते हैं",
            "blocked_list" to "ब्लॉक किए गए उपयोगकर्ताओं की सूची",
            "delete_account" to "स्थायी रूप से खाता हटाएं",
            "app_data" to "ऐप और डेटा",
            "clear_cache" to "कैश साफ करें",
            "support_social" to "सहायता और सोशल",
            "help_center" to "सहायता केंद्र / हमसे संपर्क करें",
            "report_bug" to "बग की रिपोर्ट करें",
            "share_app" to "jobaaya ऐप साझा करें",
            "rate_us" to "हमें प्ले स्टोर पर रेट करें",
            "unverified" to "असत्यापित",
            "verified_filter" to "सत्यापित",
            "blocked_filter" to "ब्लॉक किया गया",
            "home" to "होम",
            "tools" to "टूल्स",
            "profile" to "प्रोफाइल",
            "activity_logs" to "प्लेटफॉर्म गतिविधि लॉग",
            "no_activity_logs" to "कोई हालिया गतिविधि लॉग नहीं है",
            "my_profile_title" to "मेरी पेशेवर प्रोफ़ाइल",
            "prof_details" to "पेशेवर विवरण",
            "lang_sep" to "भाषा",
            "preview" to "पूर्वावलोकन",
            "service_area" to "सेवा क्षेत्र",
            "save_all" to "सभी विवरण सहेजें",
            "saved_toast" to "सहेजा गया",
            "live_map_desc" to "लाइव नेटवर्क मैप - आस-पास के स्थानीय विशेषज्ञों को खोजें",
            "loc_req" to "स्थान की अनुमति आवश्यक है",
            "loc_req_desc" to "आस-पास के पेशेवरों को देखने के लिए अनुमति दें",
            "grant_perm" to "अनुमति दें",
            "prof_proximity" to "आपके पास के पेशेवर"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_tagline" to "পেশাদার নেটওয়ার্কিং এবং ব্যবসায়িক বৃদ্ধি",
            "search_placeholder" to "পেশা, দক্ষতা বা স্থান খুঁজুন...",
            "near_me" to "আমার কাছাকাছি",
            "chats" to "চ্যাট",
            "notes" to "আমার নোট",
            "settings" to "সেটিংস",
            "admin_panel" to "অ্যাডমিন প্যানেল",
            "calculator" to "ক্যালকুলেটর",
            "bookmarks" to "বুকমার্ক",
            "login_title" to "স্বাগতম",
            "login_subtitle" to "পেশাদার নেটওয়ার্কিং প্ল্যাটফর্ম",
            "otp_login" to "ওটিপি মোবাইল লগইন",
            "email_login" to "ইমেল লগইন",
            "google_signin" to "গুগল দিয়ে লগইন করুন",
            "enter_mobile" to "মোবাইল নম্বর লিখুন",
            "enter_otp" to "৬-সংখ্যার ওটিপি লিখুন",
            "send_otp" to "ভেরিফিকেশন কোড পাঠান",
            "verify_otp" to "যাচাই করুন এবং এগিয়ে যান",
            "enter_email" to "ইমেল ঠিকানা লিখুন",
            "enter_password" to "পাসওয়ার্ড লিখুন",
            "login" to "লগইন",
            "logout" to "লগ আউট",
            "register" to "নিবন্ধন সম্পন্ন করুন",
            "select_account_type" to "আপনার অ্যাকাউন্টের ধরন নির্বাচন করুন",
            "customer" to "গ্রাহক",
            "professional" to "পেশাদার",
            "business" to "ব্যবসা",
            "full_name" to "পুরো নাম",
            "profession" to "পেশা (যেমন ইলেকট্রিশিয়ান, উকিল)",
            "skills" to "দক্ষতা",
            "mobile_number" to "মোবাইল নম্বর",
            "email" to "ইমেল ঠিকানা",
            "address" to "পুরো ঠিকানা / অবস্থান",
            "experience" to "অভিজ্ঞতা (বছরে)",
            "languages" to "ভাষা",
            "about" to "আমার সম্পর্কে / কাজের বিবরণ",
            "save_profile" to "প্রোফাইল সংরক্ষণ করুন",
            "hire_me" to "হায়ার করুন",
            "hire_now" to "তদন্ত পাঠান",
            "call" to "কল করুন",
            "whatsapp" to "হোয়াটসঅ্যাপ চ্যাট",
            "profile_views" to "প্রোফাইল ভিউ",
            "interactions" to "যোগাযোগ",
            "reviews" to "গ্রাহক রিভিউ",
            "write_review" to "রিভিউ লিখুন",
            "submit_review" to "রেটিং জমা দিন",
            "report" to "রিপোর্ট করুন",
            "block" to "ব্লক করুন",
            "sp_block_success" to "ব্যবহারকারীকে ব্লক করা হয়েছে।",
            "sp_report_success" to "প্রোফাইলটি মডারেটরদের কাছে রিপোর্ট করা হয়েছে।",
            "status_available" to "কাজের জন্য উপলব্ধ",
            "status_busy" to "বর্তমানে ব্যস্ত",
            "status_offline" to "অফলাইন",
            "working_hours" to "কাজের সময়",
            "avail_title" to "আমার প্রাপ্যতা",
            "notifications" to "অ্যাক্টিভিটি অ্যালার্ট",
            "notification_settings" to "নোটিফিকেশন সেটিংস",
            "gps_locate" to "লোকেশন শেয়ারিং চালু করুন",
            "directions" to "নির্দেশনা",
            "share_profile" to "শেয়ার করুন",
            "qr_share" to "প্রোফাইল QR কোড",
            "verified" to "যাচাইকৃত পেশাদার",
            "badge" to "ভেরিফিকেশন ব্যাজ দিন",
            "admin_users" to "অ্যাকাউন্ট ম্যানেজার",
            "admin_reports" to "রিপোর্ট অডিট লগ",
            "admin_analytics" to "অ্যানালিটিক্স ড্যাশবোর্ড",
            "create_note" to "নোট তৈরি করুন",
            "note_title" to "শিরোনাম",
            "note_body" to "কিছু লিখুন...",
            "delete" to "মুছে ফেলুন",
            "calc_title" to "সার্ভিস ক্যালকুলেটর",
            "calc_hint" to "রেট এবং কোটেশন গণনা করুন",
            "currency_counter" to "ক্যাশ কাউন্টার",
            "hiring_success" to "অভিনন্দন! আপনার তদন্ত পাঠানো হয়েছে।",
            "unlimited_msg" to "যেকোনো পেশা লিখুন। কোনো সীমাবদ্ধতা নেই।",
            "no_results" to "কোনো পেশাদার পাওয়া যায়নি।",
            "set_photo" to "প্রোফাইল ফটো সেট করুন",
            "adjust_photo" to "ফটো ঠিক করুন",
            "save_photo" to "ফটো সংরক্ষণ করুন",
            "cancel" to "বাতিল",
            "zoom_to_fit" to "ফিট করতে জুম করুন",
            "new_to_app" to "jobaaya-তে নতুন?",
            "filters" to "ফিল্টার",
            "refine_search" to "অনুসন্ধান উন্নত করুন",
            "connect" to "যুক্ত হন",
            "connected" to "যুক্ত আছেন",
            "select_language" to "ভাষা নির্বাচন করুন",
            "all" to "সব",
            "total_amount" to "মোট পরিমাণ",
            "privacy_settings" to "গোপনীয়তা সেটিংস",
            "public_mobile" to "পাবলিক মোবাইল নম্বর",
            "public_mobile_desc" to "সবাইকে আপনার কন্টাক্ট দেখতে দিন",
            "private_account" to "ব্যক্তিগত অ্যাকাউন্ট",
            "private_account_desc" to "শুধুমাত্র কানেকশনরা সব বিস্তারিত দেখতে পাবে",
            "blocked_list" to "ব্লক করা ব্যবহারকারীদের তালিকা",
            "delete_account" to "অ্যাকাউন্ট স্থায়ীভাবে মুছে ফেলুন",
            "app_data" to "অ্যাপ এবং ডেটা",
            "clear_cache" to "ক্যাশে পরিষ্কার করুন",
            "support_social" to "সাপোর্ট এবং সোশ্যাল",
            "help_center" to "হেল্প সেন্টার / আমাদের সাথে যোগাযোগ করুন",
            "report_bug" to "বাগ রিপোর্ট করুন",
            "share_app" to "অ্যাপ শেয়ার করুন",
            "rate_us" to "আমাদের রেট দিন",
            "unverified" to "অযাচাইকৃত",
            "verified_filter" to "যাচাইকৃত",
            "blocked_filter" to "ব্লক করা",
            "home" to "হোম",
            "tools" to "টুলস",
            "profile" to "প্রোফাইল",
            "activity_logs" to "অ্যাক্টিভিটি লগ",
            "no_activity_logs" to "সাম্প্রতিক কোনো অ্যাক্টিভিটি নেই",
            "my_profile_title" to "আমার পেশাদার প্রোফাইল",
            "prof_details" to "পেশাদার বিবরণ",
            "lang_sep" to "ভাষা",
            "preview" to "প্রিভিউ",
            "service_area" to "সার্ভিস এরিয়া",
            "save_all" to "সব বিবরণ সংরক্ষণ করুন",
            "saved_toast" to "সংরক্ষিত হয়েছে",
            "live_map_desc" to "লাইভ ম্যাপ - কাছাকাছি বিশেষজ্ঞদের খুঁজুন",
            "loc_req" to "লোকেশন অ্যাক্সেস প্রয়োজন",
            "loc_req_desc" to "কাছাকাছি পেশাদারদের দেখতে অনুমতি দিন",
            "grant_perm" to "অনুমতি দিন",
            "prof_proximity" to "আপনার কাছাকাছি পেশাদাররা"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_tagline" to "தொழில்முறை நெட்வொர்க்கிங் மற்றும் வணிக வளர்ச்சி",
            "search_placeholder" to "தொழில், திறன் அல்லது இடத்தைத் தேடுங்கள்...",
            "near_me" to "எனக்கு அருகில்",
            "chats" to "அரட்டைகள்",
            "notes" to "எனது குறிப்புகள்",
            "settings" to "அமைப்புகள்",
            "admin_panel" to "நிர்வாக குழு",
            "calculator" to "கணக்கீடு",
            "bookmarks" to "குறிச்சொற்கள்",
            "login_title" to "வரவேற்கிறோம்",
            "login_subtitle" to "தொழில்முறை நெட்வொர்க்கிங் தளம்",
            "otp_login" to "OTP மொபைல் உள்நுழைவு",
            "email_login" to "மின்னஞ்சல் உள்நுழைவு",
            "google_signin" to "Google மூலம் உள்நுழைக",
            "enter_mobile" to "மொபைல் எண்ணை உள்ளிடவும்",
            "enter_otp" to "6-இலக்க OTP-ஐ உள்ளிடவும்",
            "send_otp" to "சரிபார்ப்பு குறியீட்டை அனுப்பு",
            "verify_otp" to "சரிபார்த்து தொடரவும்",
            "enter_email" to "மின்னஞ்சல் முகவரியை உள்ளிடவும்",
            "enter_password" to "கடவுச்சொல்லை உள்ளிடவும்",
            "login" to "உள்நுழை",
            "logout" to "வெளியேறு",
            "register" to "பதிவை முடிக்கவும்",
            "select_account_type" to "உங்கள் கணக்கு வகையைத் தேர்ந்தெடுக்கவும்",
            "customer" to "வாடிக்கையாளர்",
            "professional" to "தொழில்முறை நிபுணர்",
            "business" to "வணிகம்",
            "full_name" to "முழு பெயர்",
            "profession" to "தொழில் (எ.கா. எலக்ட்ரீஷியன், வக்கீல்)",
            "skills" to "திறன்கள்",
            "mobile_number" to "மொபைல் எண்",
            "email" to "மின்னஞ்சல் முகவரி",
            "address" to "முழு முகவரி / இருப்பிடம்",
            "experience" to "அனுபவம் (ஆண்டுகளில்)",
            "languages" to "மொழி",
            "about" to "என்னை பற்றி / வேலை விவரங்கள்",
            "save_profile" to "சுயவிவரத்தைச் சேமி",
            "hire_me" to "வேலைக்கு அமர்த்தவும்",
            "hire_now" to "விசாரணையை அனுப்பு",
            "call" to "அழைக்கவும்",
            "whatsapp" to "வாட்ஸ்அப் அரட்டை",
            "profile_views" to "சுயவிவர பார்வைகள்",
            "interactions" to "தொடர்புகள்",
            "reviews" to "வாடிக்கையாளர் மதிப்புரைகள்",
            "write_review" to "மதிப்புரை எழுதுங்கள்",
            "submit_review" to "மதிப்பீட்டை சமர்ப்பிக்கவும்",
            "report" to "புகார் செய்",
            "block" to "தடை செய்",
            "sp_block_success" to "பயனர் வெற்றிகரமாக தடை செய்யப்பட்டார்.",
            "sp_report_success" to "சுயவிவரம் குறித்து புகார் அளிக்கப்பட்டது.",
            "status_available" to "வேலைக்கு தயார்",
            "status_busy" to "தற்போது வேலையில்",
            "status_offline" to "ஆஃப்லைன்",
            "working_hours" to "வேலை நேரம்",
            "avail_title" to "எனது இருப்பு",
            "notifications" to "அறிவிப்புகள்",
            "notification_settings" to "அறிவிப்பு அமைப்புகள்",
            "gps_locate" to "இருப்பிடத்தை பகிரவும்",
            "directions" to "திசைகள்",
            "share_profile" to "பகிரவும்",
            "qr_share" to "சுயவிவர QR குறியீடு",
            "verified" to "சரிபார்க்கப்பட்ட நிபுணர்",
            "badge" to "சரிபார்ப்பு பேட்ஜ் வழங்கவும்",
            "admin_users" to "கணக்கு மேலாளர்",
            "admin_reports" to "புகார் பதிவுகள்",
            "admin_analytics" to "புள்ளிவிவரங்கள்",
            "create_note" to "குறிப்பு உருவாக்கவும்",
            "note_title" to "தலைப்பு",
            "note_body" to "ஏதாவது எழுதுங்கள்...",
            "delete" to "நீக்கு",
            "calc_title" to "சேவை கணக்கீடு",
            "calc_hint" to "விகிதங்களை கணக்கிடுங்கள்",
            "currency_counter" to "பண எண்ணி",
            "hiring_success" to "வாழ்த்துக்கள்! உங்கள் விசாரணை அனுப்பப்பட்டது.",
            "unlimited_msg" to "எந்தவொரு தொழிலையும் உள்ளிடவும். கட்டுப்பாடுகள் இல்லை.",
            "no_results" to "நிபுணர்கள் யாரும் இல்லை.",
            "set_photo" to "சுயவிவர புகைப்படத்தை அமைக்கவும்",
            "adjust_photo" to "புகைப்படத்தை சரிசெய்யவும்",
            "save_photo" to "புகைப்படத்தைச் சேமி",
            "cancel" to "ரத்து செய்",
            "zoom_to_fit" to "பொருத்தமாக பெரிதாக்கவும்",
            "new_to_app" to "jobaaya-விற்கு புதியவரா?",
            "filters" to "வடிகட்டிகள்",
            "refine_search" to "தேடலை மேம்படுத்தவும்",
            "connect" to "இணையுங்கள்",
            "connected" to "இணைக்கப்பட்டுள்ளீர்கள்",
            "select_language" to "மொழியைத் தேர்ந்தெடுக்கவும்",
            "all" to "அனைத்தும்",
            "total_amount" to "மொத்த தொகை",
            "privacy_settings" to "தனியுரிமை அமைப்புகள்",
            "public_mobile" to "பொது மொபைல் எண்",
            "public_mobile_desc" to "எல்லோரும் உங்கள் எண்ணை பார்க்க அனுமதிக்கவும்",
            "private_account" to "தனிப்பட்ட கணக்கு",
            "private_account_desc" to "இணைப்புகள் மட்டுமே விவரங்களை பார்க்க முடியும்",
            "blocked_list" to "தடை செய்யப்பட்டவர்கள் பட்டியல்",
            "delete_account" to "கணக்கை நிரந்தரமாக நீக்கு",
            "app_data" to "செயலி மற்றும் தரவு",
            "clear_cache" to "Cache-ஐ அழிக்கவும்",
            "support_social" to "ஆதரவு மற்றும் சமூகம்",
            "help_center" to "உதவி மையம் / எங்களை தொடர்பு கொள்ளவும்",
            "report_bug" to "பிழையை புகார் செய்யவும்",
            "share_app" to "செயலியை பகிரவும்",
            "rate_us" to "எங்களை மதிப்பிடவும்",
            "unverified" to "சரிபார்க்கப்படாதது",
            "verified_filter" to "சரிபார்க்கப்பட்டது",
            "blocked_filter" to "தடை செய்யப்பட்டது",
            "home" to "முகப்பு",
            "tools" to "கருவிகள்",
            "profile" to "சுயவிவரம்",
            "activity_logs" to "செயல்பாட்டு பதிவுகள்",
            "no_activity_logs" to "சமீபத்திய செயல்பாடுகள் எதுவும் இல்லை",
            "my_profile_title" to "எனது தொழில்முறை சுயவிவரம்",
            "prof_details" to "தொழில்முறை விவரங்கள்",
            "lang_sep" to "மொழி",
            "preview" to "முன்னோட்டம்",
            "service_area" to "சேவை பகுதி",
            "save_all" to "அனைத்தையும் சேமி",
            "saved_toast" to "சேமிக்கப்பட்டது",
            "live_map_desc" to "நேரடி வரைபடம் - அருகில் உள்ள நிபுணர்களைக் கண்டறியவும்",
            "loc_req" to "இருப்பிட அணுகல் தேவை",
            "loc_req_desc" to "அருகிலுள்ளவர்களைப் பார்க்க அனுமதி வழங்கவும்",
            "grant_perm" to "அனுமதி வழங்கவும்",
            "prof_proximity" to "உங்களுக்கு அருகிலுள்ள நிபுணர்கள்"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_tagline" to "ప్రొఫెషనల్ నెట్‌వర్కింగ్ & వ్యాపార వృద్ధి",
            "search_placeholder" to "వృత్తి, నైపుణ్యం లేదా స్థానాన్ని వెతకండి...",
            "near_me" to "నా దగ్గరలో",
            "chats" to "చాట్‌లు",
            "notes" to "నా గమనికలు",
            "settings" to "సెట్టింగ్‌లు",
            "admin_panel" to "అడ్మిన్ ప్యానెల్",
            "calculator" to "క్యాలిక్యులేటర్",
            "bookmarks" to "బుక్‌మార్క్‌లు",
            "login_title" to "స్వాగతం",
            "login_subtitle" to "ప్రొఫెషనల్ నెట్‌వర్కింగ్ ప్లాట్‌ఫారమ్",
            "otp_login" to "OTP మొబైల్ లాగిన్",
            "email_login" to "ఈమెయిల్ లాగిన్",
            "google_signin" to "Googleతో సైన్ ఇన్ చేయండి",
            "enter_mobile" to "మొబైల్ నంబర్ నమోదు చేయండి",
            "enter_otp" to "6-అంకెల OTPని నమోదు చేయండి",
            "send_otp" to "ధృవీకరణ కోడ్ పంపండి",
            "verify_otp" to "ధృవీకరించి కొనసాగండి",
            "enter_email" to "ఈమెయిల్ చిరునామా నమోదు చేయండి",
            "enter_password" to "పాస్‌వర్డ్ నమోదు చేయండి",
            "login" to "లాగిన్",
            "logout" to "లాగ్ అవుట్",
            "register" to "రిజిస్ట్రేషన్ పూర్తి చేయండి",
            "select_account_type" to "మీ ఖాతా రకాన్ని ఎంచుకోండి",
            "customer" to "కస్టమర్",
            "professional" to "ప్రొఫెషనల్",
            "business" to "వ్యాపారం",
            "full_name" to "పూర్తి పేరు",
            "profession" to "వృత్తి (ఉదా. ఎలక్ట్రీషియన్, లాయర్)",
            "skills" to "నైపుణ్యాలు",
            "mobile_number" to "మొబైల్ నంబర్",
            "email" to "ఈమెయిల్ చిరునామా",
            "address" to "పూర్తి చిరునామా / ప్రాంతం",
            "experience" to "అనుభవం (సంవత్సరాలలో)",
            "languages" to "భాష",
            "about" to "నా గురించి / పని వివరాలు",
            "save_profile" to "ప్రొఫైల్‌ను సేవ్ చేయండి",
            "hire_me" to "హైర్ చేయండి",
            "hire_now" to "విచారణ పంపండి",
            "call" to "కాల్ చేయండి",
            "whatsapp" to "వాట్సాప్ చాట్",
            "profile_views" to "ప్రొఫైల్ వీక్షణలు",
            "interactions" to "పరస్పర చర్యలు",
            "reviews" to "కస్టమర్ సమీక్షలు",
            "write_review" to "సమీక్ష రాయండి",
            "submit_review" to "రేటింగ్ సమర్పించండి",
            "report" to "రిపోర్ట్ చేయండి",
            "block" to "బ్లాక్ చేయండి",
            "sp_block_success" to "వినియోగదారు విజయవంతంగా బ్లాక్ చేయబడ్డారు.",
            "sp_report_success" to "ప్రొఫైల్ రిపోర్ట్ చేయబడింది.",
            "status_available" to "పని కోసం అందుబాటులో ఉంది",
            "status_busy" to "ప్రస్తుతం బిజీగా ఉంది",
            "status_offline" to "ఆఫ్ లైన్",
            "working_hours" to "పని గంటలు",
            "avail_title" to "నా అందుబాటు",
            "notifications" to "కార్యకలాప హెచ్చరికలు",
            "notification_settings" to "నోటిఫికేషన్ సెట్టింగ్‌లు",
            "gps_locate" to "లొకేషన్ షేరింగ్‌ను ప్రారంభించండి",
            "directions" to "దిశలు",
            "share_profile" to "షేర్ చేయండి",
            "qr_share" to "ప్రొఫైల్ QR కోడ్",
            "verified" to "ధృవీకరించబడిన ప్రొఫెషనల్",
            "badge" to "ధృవీకరణ బ్యాడ్జ్ ఇవ్వండి",
            "admin_users" to "ఖాతా మేనేజర్",
            "admin_reports" to "రిపోర్ట్ ఆడిట్ లాగ్‌లు",
            "admin_analytics" to "అనలిటిక్స్ డాష్‌బోర్డ్",
            "create_note" to "నోట్ సృష్టించండి",
            "note_title" to "శీర్షిక",
            "note_body" to "ఏదైనా రాయండి...",
            "delete" to "తొలగించు",
            "calc_title" to "సర్వీస్ క్యాలిక్యులేటర్",
            "calc_hint" to "ధర మరియు కొటేషన్ లెక్కించండి",
            "currency_counter" to "క్యాష్ కౌంటర్",
            "hiring_success" to "అభినందనలు! మీ విచారణ పంపబడింది.",
            "unlimited_msg" to "ఏదైనా వృత్తిని నమోదు చేయండి. పరిమితులు లేవు.",
            "no_results" to "ప్రొఫెషనల్స్ ఎవరూ దొరకలేదు.",
            "set_photo" to "ప్రొఫైల్ ఫోటో సెట్ చేయండి",
            "adjust_photo" to "ఫోటోను సర్దుబాటు చేయండి",
            "save_photo" to "ఫోటోను సేవ్ చేయండి",
            "cancel" to "రద్దు చేయండి",
            "zoom_to_fit" to "సరిపోయేలా జూమ్ చేయండి",
            "new_to_app" to "jobaaya-కు కొత్తా?",
            "filters" to "ఫిల్టర్లు",
            "refine_search" to "శోధనను మెరుగుపరచండి",
            "connect" to "కనెక్ట్ అవ్వండి",
            "connected" to "కనెక్ట్ అయ్యారు",
            "select_language" to "భాషను ఎంచుకోండి",
            "all" to "అన్నీ",
            "total_amount" to "మొత్తం సొమ్ము",
            "privacy_settings" to "గోప్యతా సెట్టింగ్‌లు",
            "public_mobile" to "పబ్లిక్ మొబైల్ నంబర్",
            "public_mobile_desc" to "ప్రతి ఒక్కరూ మీ కాంటాక్ట్ చూడనివ్వండి",
            "private_account" to "ప్రైవేట్ ఖాతా",
            "private_account_desc" to "కనెక్షన్లు మాత్రమే పూర్తి వివరాలను చూడగలరు",
            "blocked_list" to "బ్లాక్ చేయబడిన వినియోగదారుల జాబితా",
            "delete_account" to "ఖాతాను శాశ్వతంగా తొలగించండి",
            "app_data" to "యాప్ & డేటా",
            "clear_cache" to "కాష్ క్లియర్ చేయండి",
            "support_social" to "మద్దతు & సామాజికం",
            "help_center" to "సహాయ కేంద్రం / మమ్మల్ని సంప్రదించండి",
            "report_bug" to "బగ్‌ను రిపోర్ట్ చేయండి",
            "share_app" to "యాప్‌ను షేర్ చేయండి",
            "rate_us" to "ప్లే స్టోర్‌లో మమ్మల్ని రేట్ చేయండి",
            "unverified" to "ధృవీకరించబడలేదు",
            "verified_filter" to "ధృవీకరించబడింది",
            "blocked_filter" to "బ్లాక్ చేయబడింది",
            "home" to "హోమ్",
            "tools" to "టూల్స్",
            "profile" to "ప్రొఫైల్",
            "activity_logs" to "కార్యకలాప లాగ్‌లు",
            "no_activity_logs" to "ఇటీవలి కార్యకలాపాలు లేవు",
            "my_profile_title" to "నా ప్రొఫెషనల్ ప్రొఫైల్",
            "prof_details" to "వృత్తిపరమైన వివరాలు",
            "lang_sep" to "భాష",
            "preview" to "ప్రివ్యూ",
            "service_area" to "సర్వీస్ ఏరియా",
            "save_all" to "అన్ని వివరాలను సేవ్ చేయండి",
            "saved_toast" to "సేవ్ చేయబడింది",
            "live_map_desc" to "లైవ్ మ్యాప్ - సమీప నిపుణులను కనుగొనండి",
            "loc_req" to "లొకేషన్ యాక్సెస్ అవసరం",
            "loc_req_desc" to "సమీప నిపుణులను చూడటానికి అనుమతి ఇవ్వండి",
            "grant_perm" to "అనుమతి ఇవ్వండి",
            "prof_proximity" to "మీ సమీపంలోని నిపుణులు"
        ),
        AppLanguage.ARABIC to mapOf(
            "app_tagline" to "التواصل المهني ونمو الأعمال",
            "search_placeholder" to "ابحث عن مهنة، مهارة، موقع...",
            "near_me" to "بالقرب مني",
            "chats" to "المحادثات",
            "notes" to "ملاحظاتي",
            "settings" to "الإعدادات",
            "admin_panel" to "لوحة الإدارة",
            "calculator" to "الحاسبة",
            "bookmarks" to "الإشارات المرجعية",
            "login_title" to "مرحباً بك",
            "login_subtitle" to "منصة التواصل المهني ونمو الأعمال",
            "otp_login" to "الدخول عبر رمز OTP",
            "email_login" to "الدخول عبر البريد الإلكتروني",
            "google_signin" to "تسجيل الدخول عبر جوجل",
            "enter_mobile" to "أدخل رقم الجوال",
            "enter_otp" to "أدخل رمز OTP المكون من 6 أرقام",
            "send_otp" to "إرسال رمز التحقق",
            "verify_otp" to "التحقق والمتابعة",
            "enter_email" to "أدخل البريد الإلكتروني",
            "enter_password" to "أدخل كلمة المرور",
            "login" to "تسجيل الدخول",
            "logout" to "تسجيل الخروج",
            "register" to "إكمال التسجيل",
            "select_account_type" to "اختر نوع حسابك",
            "customer" to "عميل",
            "professional" to "مهني",
            "business" to "عمل تجاري",
            "full_name" to "الاسم الكامل",
            "profession" to "المهنة (مثلاً كهربائي، محامٍ)",
            "skills" to "المهارات",
            "mobile_number" to "رقم الجوال",
            "email" to "البريد الإلكتروني",
            "address" to "العنوان الكامل / الموقع",
            "experience" to "الخبرة (بالسنوات)",
            "languages" to "اللغة",
            "about" to "عني / تفاصيل العمل",
            "save_profile" to "حفظ الملف الشخصي",
            "hire_me" to "وظفني",
            "hire_now" to "إرسال استفسار توظيف",
            "call" to "اتصل الآن",
            "whatsapp" to "دردشة واتساب",
            "profile_views" to "مشاهدات الملف الشخصي",
            "interactions" to "التفاعلات",
            "reviews" to "تقييمات العملاء",
            "write_review" to "اكتب تقييماً",
            "submit_review" to "إرسال التقييم",
            "report" to "إبلاغ",
            "block" to "حظر",
            "sp_block_success" to "تم حظر المستخدم بنجاح.",
            "sp_report_success" to "تم إبلاغ المشرفين عن الملف الشخصي.",
            "status_available" to "متاح للعمل",
            "status_busy" to "مشغول حالياً",
            "status_offline" to "غير متصل",
            "working_hours" to "ساعات العمل",
            "avail_title" to "توفري للعمل",
            "notifications" to "تنبيهات النشاط",
            "notification_settings" to "إعدادات الإشعارات",
            "gps_locate" to "تفعيل مشاركة الموقع العام",
            "directions" to "الاتجاهات",
            "share_profile" to "مشاركة الملف الشخصي",
            "qr_share" to "رمز QR للملف الشخصي",
            "verified" to "محترف موثق",
            "badge" to "منح شارة التوثيق",
            "admin_users" to "مدير الحسابات",
            "admin_reports" to "سجلات الرقابة",
            "admin_analytics" to "لوحة رؤى النمو",
            "create_note" to "إنشاء ملاحظة",
            "note_title" to "العنوان",
            "note_body" to "اكتب شيئاً...",
            "delete" to "حذف",
            "calc_title" to "حاسبة الخدمة",
            "calc_hint" to "حساب الأسعار والعروض",
            "currency_counter" to "عداد النقد",
            "hiring_success" to "مبروك! تم إرسال استفسار التوظيف الخاص بك.",
            "unlimited_msg" to "أدخل أي مهنة مخصصة. لا توجد قيود.",
            "no_results" to "لا يوجد محترفون يطابقون بحثك.",
            "set_photo" to "تعيين صورة الملف الشخصي",
            "adjust_photo" to "تعديل الصورة",
            "save_photo" to "حفظ الصورة",
            "cancel" to "إلغاء",
            "zoom_to_fit" to "تكبير للملائمة",
            "new_to_app" to "جديد في jobaaya؟",
            "filters" to "الفلاتر",
            "refine_search" to "تحسين البحث",
            "connect" to "اتصال",
            "connected" to "متصل",
            "select_language" to "اختر اللغة",
            "all" to "الكل",
            "total_amount" to "المبلغ الإجمالي",
            "privacy_settings" to "إعدادات الخصوصية",
            "public_mobile" to "رقم الجوال العام",
            "public_mobile_desc" to "السماح للجميع برؤية جهة الاتصال الخاصة بك",
            "private_account" to "حساب خاص",
            "private_account_desc" to "فقط جهات الاتصال يمكنها رؤية التفاصيل الكاملة",
            "blocked_list" to "قائمة المستخدمين المحظورين",
            "delete_account" to "حذف الحساب نهائياً",
            "app_data" to "التطبيق والبيانات",
            "clear_cache" to "مسح ذاكرة التخزين المؤقت",
            "support_social" to "الدعم والتواصل",
            "help_center" to "مركز المساعدة / اتصل بنا",
            "report_bug" to "الإبلاغ عن خلل",
            "share_app" to "مشاركة تطبيق jobaaya",
            "rate_us" to "قيمنا على المتجر",
            "unverified" to "غير موثق",
            "verified_filter" to "موثق",
            "blocked_filter" to "محظور",
            "home" to "الرئيسية",
            "tools" to "الأدوات",
            "profile" to "الملف الشخصي",
            "activity_logs" to "سجلات نشاط المنصة",
            "no_activity_logs" to "لا توجد سجلات نشاط حديثة",
            "my_profile_title" to "ملفي الشخصي المهني",
            "prof_details" to "التفاصيل المهنية",
            "lang_sep" to "اللغة",
            "preview" to "معاينة",
            "service_area" to "منطقة الخدمة",
            "save_all" to "حفظ جميع التفاصيل",
            "saved_toast" to "تم الحفظ",
            "live_map_desc" to "خريطة الشبكة الحية - ابحث عن خبراء محليين",
            "loc_req" to "مطلوب الوصول إلى الموقع",
            "loc_req_desc" to "امنح الإذن لرؤية المهنيين القريبين",
            "grant_perm" to "منح الإذن",
            "prof_proximity" to "المحترفون القريبون منك"
        ),
        AppLanguage.URDU to mapOf(
            "app_tagline" to "پیشہ ورانہ نیٹ ورکنگ اور کاروباری ترقی",
            "search_placeholder" to "پیشہ، مہارت یا جگہ تلاش کریں...",
            "near_me" to "میرے قریب",
            "chats" to "بات چیت",
            "notes" to "میرے نوٹس",
            "settings" to "ترتیبات",
            "admin_panel" to "ایڈمن پینل",
            "calculator" to "کیلکولیٹر",
            "bookmarks" to "بک مارکس",
            "login_title" to "خوش آمدید",
            "login_subtitle" to "پیشہ ورانہ ترقی اور نیٹ ورکنگ پلیٹ فارم",
            "otp_login" to "او ٹی پی موبائل لاگ ان",
            "email_login" to "ای میل لاگ ان",
            "google_signin" to "گوگل سائن ان",
            "enter_mobile" to "موبائل نمبر درج کریں",
            "enter_otp" to "6 ہندسوں کا او ٹی پی درج کریں",
            "send_otp" to "تصدیقی کوڈ بھیجیں",
            "verify_otp" to "تصدیق کریں اور آگے بڑھیں",
            "enter_email" to "ای میل ایڈریس درج کریں",
            "enter_password" to "پاس ورڈ درج کریں",
            "login" to "لاگ ان",
            "logout" to "لاگ آؤٹ",
            "register" to "رجسٹریشن مکمل کریں",
            "select_account_type" to "اپنے اکاؤنٹ کی قسم منتخب کریں",
            "customer" to "صارف",
            "professional" to "پیشہ ور",
            "business" to "کاروبار",
            "full_name" to "پورا نام",
            "profession" to "پیشہ (مثلاً الیکٹریشن، وکیل)",
            "skills" to "مہارتیں",
            "mobile_number" to "موبائل نمبر",
            "email" to "ای میل ایڈریس",
            "address" to "پورا پتہ / مقام",
            "experience" to "تجربہ (سالوں میں)",
            "languages" to "زبان",
            "about" to "میرے بارے میں / کام کی تفصیلات",
            "save_profile" to "پروفائل محفوظ کریں",
            "hire_me" to "ہائر کریں",
            "hire_now" to "پوچھ گچھ بھیجیں",
            "call" to "کال کریں",
            "whatsapp" to "واٹس ایپ چیٹ",
            "profile_views" to "پروفائل ویوز",
            "interactions" to "تعاملات",
            "reviews" to "صارفین کے جائزے",
            "write_review" to "جائزہ لکھیں",
            "submit_review" to "درجہ بندی جمع کریں",
            "report" to "رپورٹ کریں",
            "block" to "بلاک کریں",
            "sp_block_success" to "صارف کو کامیابی سے بلاک کر دیا گیا۔",
            "sp_report_success" to "پروفائل کی رپورٹ ماڈریٹرز کو کر دی گئی۔",
            "status_available" to "کام کے لیے دستیاب",
            "status_busy" to "ابھی مصروف ہے",
            "status_offline" to "آف لائن",
            "working_hours" to "کام کے اوقات",
            "avail_title" to "میری دستیابی",
            "notifications" to "سرگرمی کے الرٹس",
            "notification_settings" to "اطلاعات کی ترتیبات",
            "gps_locate" to "عوامی GPS شیئرنگ فعال کریں",
            "directions" to "راستہ دکھائیں",
            "share_profile" to "پروفائل شیئر کریں",
            "qr_share" to "پروفائل QR کوڈ",
            "verified" to "تصدیق شدہ پیشہ ور",
            "badge" to "تصدیق شدہ بیج دیں",
            "admin_users" to "اکاؤنٹ مینیجر",
            "admin_reports" to "رپورٹ اور بلاک آڈٹ",
            "admin_analytics" to "کاروباری بصیرت",
            "create_note" to "نوٹ بنائیں",
            "note_title" to "عنوان",
            "note_body" to "کچھ لکھیں...",
            "delete" to "حذف کریں",
            "calc_title" to "سروس ریٹ کیلکولیٹر",
            "calc_hint" to "ریٹ اور کوٹیشن کا حساب لگائیں",
            "currency_counter" to "کیش کاؤنٹر",
            "hiring_success" to "مبارک ہو! آپ کی پوچھ گچھ بھیج دی گئی ہے۔",
            "unlimited_msg" to "کسی بھی پیشے کو درج کریں۔ کوئی پابندی نہیں ہے۔",
            "no_results" to "کوئی پیشہ ور نہیں ملا۔ براہ کرم تلاش کے الفاظ تبدیل کریں۔",
            "set_photo" to "پروفائل فوٹو لگائیں",
            "adjust_photo" to "فوٹو درست کریں",
            "save_photo" to "فوٹو محفوظ کریں",
            "cancel" to "منسوخ کریں",
            "zoom_to_fit" to "فٹ کرنے کے لیے زوم کریں",
            "new_to_app" to "ایپ پر نئے ہیں؟",
            "filters" to "فلٹرز",
            "refine_search" to "تلاش کو بہتر بنائیں",
            "connect" to "جڑیں",
            "connected" to "جڑے ہوئے",
            "select_language" to "زبان منتخب کریں",
            "all" to "تمام",
            "total_amount" to "کل رقم",
            "privacy_settings" to "رازداری کی ترتیبات",
            "public_mobile" to "عوامی موبائل نمبر",
            "public_mobile_desc" to "ہر کسی کو اپنا رابطہ دیکھنے کی اجازت دیں",
            "private_account" to "نجی اکاؤنٹ",
            "private_account_desc" to "صرف جڑے ہوئے افراد مکمل تفصیلات دیکھ سکتے ہیں",
            "blocked_list" to "بلاک شدہ صارفین کی فہرست",
            "delete_account" to "اکاؤنٹ مستقل طور پر حذف کریں",
            "app_data" to "ایپ اور ڈیٹا",
            "clear_cache" to "کیشے صاف کریں",
            "support_social" to "سپورٹ اور سوشل",
            "help_center" to "سپورٹ سینٹر / ہم سے رابطہ کریں",
            "report_bug" to "بگ رپورٹ کریں",
            "share_app" to "ایپ شیئر کریں",
            "rate_us" to "ہمیں ریٹ کریں",
            "unverified" to "غیر تصدیق شدہ",
            "verified_filter" to "تصدیق شدہ",
            "blocked_filter" to "بلاک شدہ",
            "home" to "ہوم",
            "tools" to "ٹولز",
            "profile" to "پروفائل",
            "activity_logs" to "سرگرمی لاگز",
            "no_activity_logs" to "کوئی حالیہ سرگرمی نہیں ہے",
            "my_profile_title" to "میری پیشہ ورانہ پروفائل",
            "prof_details" to "پیشہ ورانہ تفصیلات",
            "lang_sep" to "زبان",
            "preview" to "پیش نظارہ",
            "service_area" to "سروس ایریا",
            "save_all" to "تمام تفصیلات محفوظ کریں",
            "saved_toast" to "محفوظ کر لیا گیا",
            "live_map_desc" to "لائیو میپ - قریبی ماہرین تلاش کریں",
            "loc_req" to "مقام تک رسائی درکار ہے",
            "loc_req_desc" to "قریبی لوگوں کو دیکھنے کے لیے اجازت دیں",
            "grant_perm" to "اجازت دیں",
            "prof_proximity" to "آپ کے قریب پیشہ ور"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_tagline" to "व्यावसायिक नेटवर्किंग आणि व्यवसाय वाढ",
            "search_placeholder" to "व्यवसाय, कौशल्य, स्थान शोधा...",
            "near_me" to "माझ्या जवळ",
            "chats" to "चॅट्स",
            "notes" to "माझ्या नोट्स",
            "settings" to "सेटिंग्ज",
            "admin_panel" to "अ‍ॅडमिन पॅनेल",
            "calculator" to "कॅल्क्युलेटर",
            "bookmarks" to "बुकमार्क्स",
            "login_title" to "स्वागत आहे",
            "login_subtitle" to "व्यावसायिक नेटवर्किंग आणि व्यवसाय वाढ",
            "otp_login" to "OTP मोबाईल लॉगिन",
            "email_login" to "ईमेल लॉगिन",
            "google_signin" to "Google सह साइन-इन",
            "enter_mobile" to "मोबाईल नंबर टाका",
            "enter_otp" to "6-अंकी OTP टाका",
            "send_otp" to "व्हेरिफिकेशन कोड पाठवा",
            "verify_otp" to "व्हेरिफाय करा आणि पुढे जा",
            "enter_email" to "ईमेल पत्ता टाका",
            "enter_password" to "पासवर्ड टाका",
            "login" to "लॉगिन",
            "logout" to "लॉग आउट",
            "register" to "नोंदणी पूर्ण करा",
            "select_account_type" to "तुमचा खाते प्रकार निवडा",
            "customer" to "ग्राहक",
            "professional" to "व्यावसायिक",
            "business" to "व्यवसाय",
            "full_name" to "पूर्ण नाव",
            "profession" to "व्यवसाय (उदा. इलेक्ट्रिशियन, वकील)",
            "skills" to "कौशल्ये",
            "mobile_number" to "मोबाईल नंबर",
            "email" to "ईमेल पत्ता",
            "address" to "पूर्ण पत्ता / स्थान",
            "experience" to "अनुभवाची वर्षे",
            "languages" to "भाषा",
            "about" to "माझ्याबद्दल / कामाचे तपशील",
            "save_profile" to "प्रोफाइल जतन करा",
            "hire_me" to "हायर करा",
            "hire_now" to "चौकशी पाठवा",
            "call" to "कॉल करा",
            "whatsapp" to "व्हॉट्सअ‍ॅप चॅट",
            "profile_views" to "प्रोफाइल व्ह्यूज",
            "interactions" to "संवाद",
            "reviews" to "ग्राहक पुनरावलोकने",
            "write_review" to "पुनरावलोकन लिहा",
            "submit_review" to "रेटिंग सबमिट करा",
            "report" to "रिपोर्ट करा",
            "block" to "ब्लॉक करा",
            "sp_block_success" to "वापरकर्ता यशस्वीरित्या ब्लॉक केला.",
            "sp_report_success" to "प्रोफाइल मोडरेटरना रिपोर्ट केली.",
            "status_available" to "कामासाठी उपलब्ध",
            "status_busy" to "सध्या व्यस्त",
            "status_offline" to "ऑफलाइन",
            "working_hours" to "कामाचे तास",
            "avail_title" to "माझी उपलब्धता",
            "notifications" to "सूचना",
            "notification_settings" to "पुश नोटिफिकेशन्स",
            "gps_locate" to "GPS शेअरिंग सक्षम करा",
            "directions" to "मार्ग मिळवा",
            "share_profile" to "प्रोफाइल शेअर करा",
            "qr_share" to "प्रोफाइल QR कोड",
            "verified" to "सत्यापित व्यावसायिक",
            "badge" to "व्हेरिफिकेशन बॅज द्या",
            "admin_users" to "खाते व्यवस्थापक",
            "admin_reports" to "मोडरेशन लॉग",
            "admin_analytics" to "विकास विश्लेषण",
            "create_note" to "नोट तयार करा",
            "note_title" to "शीर्षक",
            "note_body" to "काहीतरी लिहा...",
            "delete" to "हटवा",
            "calc_title" to "सेवा कॅल्क्युलेटर",
            "calc_hint" to "दर आणि कोटेशनची गणना करा",
            "currency_counter" to "कॅश काउंटर",
            "hiring_success" to "अभिनंदन! तुमची चौकशी पाठवली गेली आहे.",
            "unlimited_msg" to "कोणताही व्यवसाय प्रविष्ट करा. कोणतेही निर्बंध नाहीत.",
            "no_results" to "तुमच्या फिल्टरशी जुळणारे व्यावसायिक नाहीत.",
            "set_photo" to "प्रोफाइल फोटो सेट करा",
            "adjust_photo" to "फोटो अ‍ॅडजस्ट करा",
            "save_photo" to "फोटो जतन करा",
            "cancel" to "रद्द करा",
            "zoom_to_fit" to "फिट करण्यासाठी झूम करा",
            "new_to_app" to "jobaaya वर नवीन आहात?",
            "filters" to "फिल्टर्स",
            "refine_search" to "शोध सुधारा",
            "connect" to "कनेक्ट व्हा",
            "connected" to "कनेक्टेड",
            "select_language" to "भाषा निवडा",
            "all" to "सर्व",
            "total_amount" to "एकूण रक्कम",
            "privacy_settings" to "गोपनीयता सेटिंग्ज",
            "public_mobile" to "सार्वजनिक मोबाईल नंबर",
            "public_mobile_desc" to "प्रत्येकाला तुमचा संपर्क पाहू द्या",
            "private_account" to "खाजगी खाते",
            "private_account_desc" to "केवळ कनेक्शन्स पूर्ण तपशील पाहू शकतात",
            "blocked_list" to "ब्लॉक केलेल्या वापरकर्त्यांची यादी",
            "delete_account" to "खाते कायमचे हटवा",
            "app_data" to "अ‍ॅप आणि डेटा",
            "clear_cache" to "कॅशे साफ करा",
            "support_social" to "सपोर्ट आणि सोशल",
            "help_center" to "मदत केंद्र / आमच्याशी संपर्क साधा",
            "report_bug" to "बग रिपोर्ट करा",
            "share_app" to "अ‍ॅप शेअर करा",
            "rate_us" to "प्ले स्टोअरवर आम्हाला रेट करा",
            "unverified" to "असत्यापित",
            "verified_filter" to "सत्यापित",
            "blocked_filter" to "ब्लॉक केलेले",
            "home" to "होम",
            "tools" to "टूल्स",
            "profile" to "प्रोफाइल",
            "activity_logs" to "प्लॅटफॉर्म अ‍ॅक्टिव्हिटी लॉग",
            "no_activity_logs" to "अलीकडील अ‍ॅक्टिव्हिटी लॉग नाहीत",
            "my_profile_title" to "माझी व्यावसायिक प्रोफाइल",
            "prof_details" to "व्यावसायिक तपशील",
            "lang_sep" to "भाषा",
            "preview" to "पूर्वावलोकन",
            "service_area" to "सेवा क्षेत्र",
            "save_all" to "सर्व तपशील जतन करा",
            "saved_toast" to "जतन केले",
            "live_map_desc" to "लाईव्ह नेटवर्क मॅप - जवळचे तज्ञ शोधा",
            "loc_req" to "स्थान प्रवेश आवश्यक",
            "loc_req_desc" to "जवळपासचे व्यावसायिक पाहण्यासाठी परवानगी द्या",
            "grant_perm" to "परवानगी द्या",
            "prof_proximity" to "तुमच्या जवळचे व्यावसायिक"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_tagline" to "વ્યાવસાયિક નેટવર્કિંગ અને વ્યવસાય વૃદ્ધિ",
            "search_placeholder" to "વ્યવસાય, કૌશલ્ય અથવા સ્થળ શોધો...",
            "near_me" to "મારી નજીક",
            "chats" to "ચેટ્સ",
            "notes" to "મારી નોંધો",
            "settings" to "સેટિંગ્સ",
            "admin_panel" to "એડમિન પેનલ",
            "calculator" to "કેલ્ક્યુલેટર",
            "bookmarks" to "બુકમાર્ક્સ",
            "login_title" to "સ્વાગત છે",
            "login_subtitle" to "વ્યાવસાયિક નેટવર્કિંગ અને વ્યવસાય વૃદ્ધિ",
            "otp_login" to "OTP મોબાઈલ લોગિન",
            "email_login" to "ઈમેલ લોગિન",
            "google_signin" to "Google સાથે સાઇન-ઇન",
            "enter_mobile" to "મોબાઈલ નંબર દાખલ કરો",
            "enter_otp" to "6-અંકનો OTP દાખલ કરો",
            "send_otp" to "વેરિફિકેશન કોડ મોકલો",
            "verify_otp" to "વેરિફાય કરો અને આગળ વધો",
            "enter_email" to "ઈમેલ સરનામું દાખલ કરો",
            "enter_password" to "પાસવર્ડ દાખલ કરો",
            "login" to "લોગિન",
            "logout" to "લોગ આઉટ",
            "register" to "નોંધણી પૂર્ણ કરો",
            "select_account_type" to "તમારો ખાતાનો પ્રકાર પસંદ કરો",
            "customer" to "ગ્રાહક",
            "professional" to "વ્યાવસાયિક",
            "business" to "વ્યવસાય",
            "full_name" to "પૂરું નામ",
            "profession" to "વ્યવસાય (દા.ત. ઈલેક્ટ્રીશિયન, વકીલ)",
            "skills" to "કૌશલ્યો",
            "mobile_number" to "મોબાઈલ નંબર",
            "email" to "ઈમેલ સરનામું",
            "address" to "પૂરું સરનામું / સ્થાન",
            "experience" to "અનુભવના વર્ષો",
            "languages" to "ભાષા",
            "about" to "મારા વિશે / કામની વિગતો",
            "save_profile" to "પ્રોફાઇલ સાચવો",
            "hire_me" to "હાયર કરો",
            "hire_now" to "તપાસ મોકલો",
            "call" to "કોલ કરો",
            "whatsapp" to "વોટ્સએપ ચેટ",
            "profile_views" to "પ્રોફાઇલ વ્યૂઝ",
            "interactions" to "સંવાદો",
            "reviews" to "ગ્રાહક સમીક્ષાઓ",
            "write_review" to "સમીક્ષા લખો",
            "submit_review" to "રેટિંગ સબમિટ કરો",
            "report" to "રિપોર્ટ કરો",
            "block" to "બ્લોક કરો",
            "sp_block_success" to "વપરાશકર્તા સફળતાપૂર્વક બ્લોક થયો.",
            "sp_report_success" to "પ્રોફાઇલ મોડરેટરોને રિપોર્ટ કરવામાં આવી.",
            "status_available" to "કામ માટે ઉપલબ્ધ",
            "status_busy" to "અત્યારે વ્યસ્ત",
            "status_offline" to "ઓફલાઇન",
            "working_hours" to "કામના કલાકો",
            "avail_title" to "મારી ઉપલબ્ધતા",
            "notifications" to "સૂચનાઓ",
            "notification_settings" to "પુશ નોટિફિકેશન",
            "gps_locate" to "GPS શેરિંગ સક્ષમ કરો",
            "directions" to "માર્ગ મેળવો",
            "share_profile" to "પ્રોફાઇલ શેર કરો",
            "qr_share" to "પ્રોફાઇલ QR કોડ",
            "verified" to "ચકાસાયેલ વ્યાવસાયિક",
            "badge" to "વેરિફિકેશન બેજ આપો",
            "admin_users" to "એકાઉન્ટ મેનેજર",
            "admin_reports" to "મોડરેશન ઓડિટ લોગ્સ",
            "admin_analytics" to "વૃદ્ધિ વિશ્લેષણ ડેશબોર્ડ",
            "create_note" to "નોંધ બનાવો",
            "note_title" to "શીર્ષક",
            "note_body" to "કંઈક લખો...",
            "delete" to "ડિલીટ",
            "calc_title" to "સેવા કેલ્ક્યુલેટર",
            "calc_hint" to "દર અને કોટેશનની ગણતરી કરો",
            "currency_counter" to "કેશ કાઉન્ટર",
            "hiring_success" to "અભિનંદન! તમારી તપાસ મોકલવામાં આવી છે.",
            "unlimited_msg" to "કોઈપણ વ્યવસાય દાખલ કરો. કોઈ પ્રતિબંધો નથી.",
            "no_results" to "કોઈ વ્યાવસાયિકો તમારી શોધ સાથે મેળ ખાતા નથી.",
            "set_photo" to "પ્રોફાઇલ ફોટો સેટ કરો",
            "adjust_photo" to "ફોટો એડજસ્ટ કરો",
            "save_photo" to "ફોટો સાચવો",
            "cancel" to "રદ કરો",
            "zoom_to_fit" to "ફિટ કરવા માટે ઝૂમ કરો",
            "new_to_app" to "jobaaya પર નવા છો?",
            "filters" to "ફિલ્ટર્સ",
            "refine_search" to "શોધ સુધારો",
            "connect" to "કનેક્ટ થાઓ",
            "connected" to "કનેક્ટેડ",
            "select_language" to "ભાષા પસંદ કરો",
            "all" to "બધા",
            "total_amount" to "કુલ રકમ",
            "privacy_settings" to "ગોપનીયતા સેટિંગ્સ",
            "public_mobile" to "જાહેર મોબાઈલ નંબર",
            "public_mobile_desc" to "દરેકને તમારો સંપર્ક જોવા દો",
            "private_account" to "ખાનગી ખાતું",
            "private_account_desc" to "ફક્ત કનેક્શન્સ જ વિગતો જોઈ શકે છે",
            "blocked_list" to "બ્લોક કરેલા વપરાશકર્તાઓની યાદી",
            "delete_account" to "ખાતું કાયમ માટે કાઢી નાખો",
            "app_data" to "એપ્લિકેશન અને ડેટા",
            "clear_cache" to "કેશ સાફ કરો",
            "support_social" to "સપોર્ટ અને સોશિયલ",
            "help_center" to "મદદ કેન્દ્ર / અમારો સંપર્ક કરો",
            "report_bug" to "બગ રિપોર્ટ કરો",
            "share_app" to "એપ્લિકેશન શેર કરો",
            "rate_us" to "અમને રેટ કરો",
            "unverified" to "અસત્યાપિત",
            "verified_filter" to "ચકાસાયેલ",
            "blocked_filter" to "બ્લોક કરેલ",
            "home" to "હોમ",
            "tools" to "ટૂલ્સ",
            "profile" to "પ્રોફાઇલ",
            "activity_logs" to "પ્લેટફોર્મ પ્રવૃત્તિ લોગ્સ",
            "no_activity_logs" to "કોઈ તાજેતરના પ્રવૃત્તિ લોગ નથી",
            "my_profile_title" to "મારી વ્યાવસાયિક પ્રોફાઇલ",
            "prof_details" to "વ્યાવસાયિક વિગતો",
            "lang_sep" to "ભાષા",
            "preview" to "પૂર્વાવલોકન",
            "service_area" to "સેવા વિસ્તાર",
            "save_all" to "બધી વિગતો સાચવો",
            "saved_toast" to "સાચવેલ",
            "live_map_desc" to "લાઇવ નેટવર્ક નકશો - નજીકના નિષ્ણાતો શોધો",
            "loc_req" to "સ્થાન એક્સેસ જરૂરી",
            "loc_req_desc" to "નજીકના વ્યાવસાયિકોને જોવા માટે પરવાનગી આપો",
            "grant_perm" to "પરવાનગી આપો",
            "prof_proximity" to "તમારી નજીકના વ્યાવસાયિકો"
        ),
        AppLanguage.PUNJABI to mapOf(
            "app_tagline" to "ਪੇਸ਼ੇਵਰ ਨੈੱਟਵਰਕਿੰਗ ਅਤੇ ਕਾਰੋਬਾਰੀ ਵਿਕਾਸ",
            "search_placeholder" to "ਪੇਸ਼ਾ, ਹੁਨਰ ਜਾਂ ਸਥਾਨ ਲੱਭੋ...",
            "near_me" to "ਮੇਰੇ ਨੇੜੇ",
            "chats" to "ਚੈਟਸ",
            "notes" to "ਮੇਰੇ ਨੋਟਸ",
            "settings" to "ਸੈਟਿੰਗਾਂ",
            "admin_panel" to "ਐਡਮਿਨ ਪੈਨਲ",
            "calculator" to "ਕੈਲਕੁਲੇਟਰ",
            "bookmarks" to "ਬੁੱਕਮਾਰਕਸ",
            "login_title" to "ਸਵਾਗਤ ਹੈ",
            "login_subtitle" to "ਪੇਸ਼ੇਵਰ ਨੈੱਟਵਰਕਿੰਗ ਅਤੇ ਕਾਰੋਬਾਰੀ ਵਿਕਾਸ",
            "otp_login" to "OTP ਮੋਬਾਈਲ ਲੌਗਇਨ",
            "email_login" to "ਈਮੇਲ ਲੌਗਇਨ",
            "google_signin" to "Google ਨਾਲ ਸਾਈਨ-ਇਨ",
            "enter_mobile" to "ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
            "enter_otp" to "6-ਅੰਕਾਂ ਦਾ OTP ਦਰਜ ਕਰੋ",
            "send_otp" to "ਵੈਰੀਫਿਕੇਸ਼ਨ ਕੋਡ ਭੇਜੋ",
            "verify_otp" to "ਵੈਰੀਫਾਈ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ",
            "enter_email" to "ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ",
            "enter_password" to "ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ",
            "login" to "ਲੌਗਇਨ",
            "logout" to "ਲੌਗ ਆਉਟ",
            "register" to "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰੋ",
            "select_account_type" to "ਆਪਣਾ ਖਾਤਾ ਕਿਸਮ ਚੁਣੋ",
            "customer" to "ਗਾਹਕ",
            "professional" to "ਪੇਸ਼ੇਵਰ",
            "business" to "ਕਾਰੋਬਾਰ",
            "full_name" to "ਪੂਰਾ ਨਾਮ",
            "profession" to "ਪੇਸ਼ਾ (ਜਿਵੇਂ ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ, ਵਕੀਲ)",
            "skills" to "ਹੁਨਰ",
            "mobile_number" to "ਮੋਬਾਈਲ ਨੰਬਰ",
            "email" to "ਈਮੇਲ ਪਤਾ",
            "address" to "ਪੂਰਾ ਪਤਾ / ਸਥਾਨ",
            "experience" to "ਤਜ਼ਰਬੇ ਦੇ ਸਾਲ",
            "languages" to "ਭਾਸ਼ਾ",
            "about" to "ਮੇਰੇ ਬਾਰੇ / ਕੰਮ ਦਾ ਵੇਰਵਾ",
            "save_profile" to "ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕਰੋ",
            "hire_me" to "ਹਾਇਰ ਕਰੋ",
            "hire_now" to "ਪੁੱਛਗਿੱਛ ਭੇਜੋ",
            "call" to "ਕਾਲ ਕਰੋ",
            "whatsapp" to "ਵਟਸਐਪ ਚੈਟ",
            "profile_views" to "ਪ੍ਰੋਫਾਈਲ ਵਿਊਜ਼",
            "interactions" to "ਗੱਲਬਾਤ",
            "reviews" to "ਗਾਹਕ ਸਮੀਖਿਆਵਾਂ",
            "write_review" to "ਸਮੀਖਿਆ ਲਿਖੋ",
            "submit_review" to "ਰੇਟਿੰਗ ਸਬਮਿਟ ਕਰੋ",
            "report" to "ਰਿਪੋਰਟ ਕਰੋ",
            "block" to "ਬਲਾਕ ਕਰੋ",
            "sp_block_success" to "ਵਰਤੋਂਕਾਰ ਨੂੰ ਸਫਲਤਾਪੂਰਵਕ ਬਲਾਕ ਕਰ ਦਿੱਤਾ ਗਿਆ।",
            "sp_report_success" to "ਪ੍ਰੋਫਾਈਲ ਦੀ ਰਿਪੋਰਟ ਮੋਡਰੇਟਰਾਂ ਨੂੰ ਕੀਤੀ ਗਈ।",
            "status_available" to "ਕੰਮ ਲਈ ਉਪਲਬਧ",
            "status_busy" to "ਹੁਣੇ ਰੁੱਝਿਆ ਹੋਇਆ",
            "status_offline" to "ਆਫਲਾਈਨ",
            "working_hours" to "ਕੰਮ ਦੇ ਘੰਟੇ",
            "avail_title" to "ਮੇਰੀ ਉਪਲਬਧਤਾ",
            "notifications" to "ਨੋਟੀਫਿਕੇਸ਼ਨ",
            "notification_settings" to "ਪੁਸ਼ ਨੋਟੀਫਿਕੇਸ਼ਨ",
            "gps_locate" to "GPS ਸ਼ੇਅਰਿੰਗ ਚਾਲੂ ਕਰੋ",
            "directions" to "ਰਾਸਤਾ ਦੇਖੋ",
            "share_profile" to "ਪ੍ਰੋਫਾਈਲ ਸ਼ੇਅਰ ਕਰੋ",
            "qr_share" to "ਪ੍ਰੋਫਾਈਲ QR ਕੋਡ",
            "verified" to "ਤਸਦੀਕ ਪੇਸ਼ੇਵਰ",
            "badge" to "ਵੈਰੀਫਿਕੇਸ਼ਨ ਬੈਜ ਦਿਓ",
            "admin_users" to "ਖਾਤਾ ਪ੍ਰਬੰਧਕ",
            "admin_reports" to "ਮੋਡਰੇਸ਼ਨ ਆਡਿਟ ਲੌਗਸ",
            "admin_analytics" to "ਵਿਕਾਸ ਵਿਸ਼ਲੇਸ਼ਣ ਡੈਸ਼ਬੋਰਡ",
            "create_note" to "ਨੋਟ ਬਣਾਓ",
            "note_title" to "ਸਿਰਲੇਖ",
            "note_body" to "ਕੁਝ ਲਿਖੋ...",
            "delete" to "ਮਿਟਾਓ",
            "calc_title" to "ਸੇਵਾ ਕੈਲਕੁਲੇਟਰ",
            "calc_hint" to "ਦਰਾਂ ਅਤੇ ਕੋਟੇਸ਼ਨਾਂ ਦੀ ਗਣਨਾ ਕਰੋ",
            "currency_counter" to "ਕੈਸ਼ ਕਾਊਂਟਰ",
            "hiring_success" to "ਵਧਾਈਆਂ! ਤੁਹਾਡੀ ਪੁੱਛਗਿੱਛ ਭੇਜ ਦਿੱਤੀ ਗਈ ਹੈ।",
            "unlimited_msg" to "ਕੋਈ ਵੀ ਪੇਸ਼ਾ ਦਰਜ ਕਰੋ। ਕੋਈ ਪਾਬੰਦੀ ਨਹੀਂ ਹੈ।",
            "no_results" to "ਕੋਈ ਪੇਸ਼ੇਵਰ ਤੁਹਾਡੀ ਖੋਜ ਨਾਲ ਮੇਲ ਨਹੀਂ ਖਾਂਦਾ।",
            "set_photo" to "ਪ੍ਰੋਫਾਈਲ ਫੋਟੋ ਲਗਾਓ",
            "adjust_photo" to "ਫੋਟੋ ਠੀਕ ਕਰੋ",
            "save_photo" to "ਫੋਟੋ ਸੇਵ ਕਰੋ",
            "cancel" to "ਰੱਦ ਕਰੋ",
            "zoom_to_fit" to "ਫਿੱਟ ਕਰਨ ਲਈ ਜ਼ੂਮ ਕਰੋ",
            "new_to_app" to "jobaaya 'ਤੇ ਨਵੇਂ ਹੋ?",
            "filters" to "ਫਿਲਟਰ",
            "refine_search" to "ਖੋਜ ਵਿੱਚ ਸੁਧਾਰ ਕਰੋ",
            "connect" to "ਕਨੈਕਟ ਹੋਵੋ",
            "connected" to "ਕਨੈਕਟਡ",
            "select_language" to "ਭਾਸ਼ਾ ਚੁਣੋ",
            "all" to "ਸਭ",
            "total_amount" to "ਕੁੱਲ ਰਕਮ",
            "privacy_settings" to "ਪਰਾਈਵੇਸੀ ਸੈਟਿੰਗਾਂ",
            "public_mobile" to "ਜਨਤਕ ਮੋਬਾਈਲ ਨੰਬਰ",
            "public_mobile_desc" to "ਹਰ ਕਿਸੇ ਨੂੰ ਤੁਹਾਡਾ ਸੰਪਰਕ ਦੇਖਣ ਦਿਓ",
            "private_account" to "ਨਿੱਜੀ ਖਾਤਾ",
            "private_account_desc" to "ਸਿਰਫ਼ ਕਨੈਕਸ਼ਨ ਹੀ ਵੇਰਵੇ ਦੇਖ ਸਕਦੇ ਹਨ",
            "blocked_list" to "ਬਲਾਕ ਕੀਤੇ ਵਰਤੋਂਕਾਰਾਂ ਦੀ ਸੂਚੀ",
            "delete_account" to "ਖਾਤਾ ਪੱਕੇ ਤੌਰ 'ਤੇ ਮਿਟਾਓ",
            "app_data" to "ਐਪ ਅਤੇ ਡਾਟਾ",
            "clear_cache" to "ਕੈਸ਼ੇ ਸਾਫ਼ ਕਰੋ",
            "support_social" to "ਸਪੋਰਟ ਅਤੇ ਸੋਸ਼ਲ",
            "help_center" to "ਮਦਦ ਕੇਂਦਰ / ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
            "report_bug" to "ਬਗ ਰਿਪੋਰਟ ਕਰੋ",
            "share_app" to "ਐਪ ਸ਼ੇਅਰ ਕਰੋ",
            "rate_us" to "ਸਾਨੂੰ ਪਲੇ ਸਟੋਰ 'ਤੇ ਰੇਟ ਕਰੋ",
            "unverified" to "ਗੈਰ-ਤਸਦੀਕ",
            "verified_filter" to "ਤਸਦੀਕ",
            "blocked_filter" to "ਬਲਾਕ ਕੀਤਾ ਗਿਆ",
            "home" to "ਹੋਮ",
            "tools" to "ਟੂਲਸ",
            "profile" to "ਪ੍ਰੋਫਾਈਲ",
            "activity_logs" to "ਪਲੇਟਫਾਰਮ ਸਰਗਰਮੀ ਲੌਗਸ",
            "no_activity_logs" to "ਕੋਈ ਤਾਜ਼ਾ ਸਰਗਰਮੀ ਲੌਗ ਨਹੀਂ ਹੈ",
            "my_profile_title" to "ਮੇਰੀ ਪੇਸ਼ੇਵਰ ਪ੍ਰੋਫਾਈਲ",
            "prof_details" to "ਪੇਸ਼ੇਵਰ ਵੇਰਵੇ",
            "lang_sep" to "ਭਾਸ਼ਾ",
            "preview" to "ਪੂਰਵਦਰਸ਼ਨ",
            "service_area" to "ਸੇਵਾ ਖੇਤਰ",
            "save_all" to "ਸਾਰੇ ਵੇਰਵੇ ਸੇਵ ਕਰੋ",
            "saved_toast" to "ਸੇਵ ਕੀਤਾ ਗਿਆ",
            "live_map_desc" to "ਲਾਈਵ ਨੈੱਟਵਰਕ ਮੈਪ - ਨੇੜਲੇ ਮਾਹਿਰਾਂ ਨੂੰ ਲੱਭੋ",
            "loc_req" to "ਲੋਕੇਸ਼ਨ ਐਕਸੈਸ ਦੀ ਲੋੜ ਹੈ",
            "loc_req_desc" to "ਨੇੜਲੇ ਪੇਸ਼ੇਵਰਾਂ ਨੂੰ ਦੇਖਣ ਲਈ ਇਜਾਜ਼ਤ ਦਿਓ",
            "grant_perm" to "ਇਜਾਜ਼ਤ ਦਿਓ",
            "prof_proximity" to "ਤੁਹਾਡੇ ਨੇੜਲੇ ਪੇਸ਼ੇਵਰ"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_tagline" to "പ്രൊഫഷണൽ നെറ്റ്വർക്കിംഗും ബിസിനസ്സ് വളർച്ചയും",
            "search_placeholder" to "തൊഴിൽ, വൈദഗ്ധ്യം അല്ലെങ്കിൽ സ്ഥലം തിരയുക...",
            "near_me" to "എന്റെ അടുത്ത്",
            "chats" to "ചാറ്റുകൾ",
            "notes" to "എന്റെ കുറിപ്പുകൾ",
            "settings" to "ക്രമീകരണങ്ങൾ",
            "admin_panel" to "അഡ്മിൻ പാനൽ",
            "calculator" to "കാൽക്കുലേറ്റർ",
            "bookmarks" to "ബുക്ക്മാർക്കുകൾ",
            "login_title" to "സ്വാഗതം",
            "login_subtitle" to "പ്രൊഫഷണൽ നെറ്റ്വർക്കിംഗും ബിസിനസ്സ് വളർച്ചയും",
            "otp_login" to "OTP മൊബൈൽ ലോഗിൻ",
            "email_login" to "ഇമെയിൽ ലോഗിൻ",
            "google_signin" to "Google ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക",
            "enter_mobile" to "മൊബൈൽ നമ്പർ നൽകുക",
            "enter_otp" to "6 അക്ക OTP നൽകുക",
            "send_otp" to "വെരിഫിക്കേഷൻ കോഡ് അയയ്ക്കുക",
            "verify_otp" to "വെരിഫൈ ചെയ്ത് മുന്നോട്ട് പോകുക",
            "enter_email" to "ഇമെയിൽ വിലാസം നൽകുക",
            "enter_password" to "പാസ്‌വേഡ് നൽകുക",
            "login" to "ലോഗിൻ",
            "logout" to "ലോഗ് ഔട്ട്",
            "register" to "രജിസ്ട്രേഷൻ പൂർത്തിയാക്കുക",
            "select_account_type" to "അക്കൗണ്ട് തരം തിരഞ്ഞെടുക്കുക",
            "customer" to "കസ്റ്റമർ",
            "professional" to "പ്രൊഫഷണൽ",
            "business" to "ബിസിനസ്സ്",
            "full_name" to "മുഴുവൻ പേര്",
            "profession" to "തൊഴിൽ (ഉദാ: ഇലക്ട്രീഷ്യൻ, വക്കീൽ)",
            "skills" to "നൈപുണ്യങ്ങൾ",
            "mobile_number" to "മൊബൈൽ നമ്പർ",
            "email" to "ഇമെയിൽ വിലാസം",
            "address" to "മുഴുവൻ വിലാസം / സ്ഥലം",
            "experience" to "പ്രവൃത്തിപരിചയം (വർഷങ്ങളിൽ)",
            "languages" to "ഭാഷ",
            "about" to "എന്നെക്കുറിച്ച് / ജോലി വിവരങ്ങൾ",
            "save_profile" to "പ്രൊഫൈൽ സംരക്ഷിക്കുക",
            "hire_me" to "ഹയർ ചെയ്യുക",
            "hire_now" to "അന്വേഷണം അയയ്ക്കുക",
            "call" to "ഇപ്പോൾ വിളിക്കുക",
            "whatsapp" to "വാട്ട്‌സ്ആപ്പ് ചാറ്റ്",
            "profile_views" to "പ്രൊഫൈൽ വ്യൂസ്",
            "interactions" to "ഇടപെടലുകൾ",
            "reviews" to "കസ്റ്റമർ റിവ്യൂകൾ",
            "write_review" to "റിവ്യൂ എഴുതുക",
            "submit_review" to "റേറ്റിംഗ് സമർപ്പിക്കുക",
            "report" to "റിപ്പോർട്ട് ചെയ്യുക",
            "block" to "ബ്ലോക്ക് ചെയ്യുക",
            "sp_block_success" to "ഉപയോക്താവിനെ വിജയകരമായി ബ്ലോക്ക് ചെയ്തു.",
            "sp_report_success" to "പ്രൊഫൈൽ റിപ്പോർട്ട് ചെയ്തു.",
            "status_available" to "ജോലിക്ക് ലഭ്യമാണ്",
            "status_busy" to "നിലവിൽ തിരക്കിലാണ്",
            "status_offline" to "ഓഫ്‌ലൈൻ",
            "working_hours" to "ജോലി സമയം",
            "avail_title" to "ലഭ്യത",
            "notifications" to "അറിയിപ്പുകൾ",
            "notification_settings" to "നോട്ടിഫിക്കേഷൻ ക്രമീകരണങ്ങൾ",
            "gps_locate" to "ലൊക്കേഷൻ പങ്കിടൽ പ്രവർത്തനക്ഷമമാക്കുക",
            "directions" to "വഴി അറിയുക",
            "share_profile" to "പ്രൊഫൈൽ പങ്കിടുക",
            "qr_share" to "പ്രൊഫൈൽ QR കോഡ്",
            "verified" to "സ്ഥിരീകരിച്ച പ്രൊഫഷണൽ",
            "badge" to "വെരിഫിക്കേഷൻ ബാഡ്ജ് നൽകുക",
            "admin_users" to "അക്കൗണ്ട് മാനേജർ",
            "admin_reports" to "റിപ്പോർട്ട് ഓഡിറ്റ് ലോഗുകൾ",
            "admin_analytics" to "ഗ്രോത്ത് അനലിറ്റിക്സ്",
            "create_note" to "കുറിപ്പ് സൃഷ്ടിക്കുക",
            "note_title" to "തലക്കെട്ട്",
            "note_body" to "എന്തെങ്കിലും എഴുതുക...",
            "delete" to "ഇല്ലാതാക്കുക",
            "calc_title" to "സർവീസ് കാൽക്കുലേറ്റർ",
            "calc_hint" to "നിരക്കുകൾ കണക്കാക്കുക",
            "currency_counter" to "ക്യാഷ് കൗണ്ടർ",
            "hiring_success" to "അഭിനന്ദനങ്ങൾ! നിങ്ങളുടെ അന്വേഷണം അയച്ചു.",
            "unlimited_msg" to "ഏതൊരു തൊഴിലും നൽകുക. നിയന്ത്രണങ്ങളില്ല.",
            "no_results" to "അനുയോജ്യമായ പ്രൊഫഷണലുകളെ കണ്ടെത്തിയില്ല.",
            "set_photo" to "പ്രൊഫൈൽ ഫോട്ടോ സെറ്റ് ചെയ്യുക",
            "adjust_photo" to "ഫോട്ടോ ക്രമീകരിക്കുക",
            "save_photo" to "ഫോട്ടോ സംരക്ഷിക്കുക",
            "cancel" to "റദ്ദാക്കുക",
            "zoom_to_fit" to "സൂം ചെയ്യുക",
            "new_to_app" to "jobaaya-യിൽ പുതിയതാണോ?",
            "filters" to "ഫിൽട്ടറുകൾ",
            "refine_search" to "തിരയൽ മെച്ചപ്പെടുത്തുക",
            "connect" to "കണക്ട് ചെയ്യുക",
            "connected" to "കണക്ട് ആയി",
            "select_language" to "ഭാഷ തിരഞ്ഞെടുക്കുക",
            "all" to "എല്ലാം",
            "total_amount" to "ആകെ തുക",
            "privacy_settings" to "സ്വകാര്യതാ ക്രമീകരണങ്ങൾ",
            "public_mobile" to "പൊതു മൊബൈൽ നമ്പർ",
            "public_mobile_desc" to "എല്ലാവർക്കും നിങ്ങളുടെ കോൺടാക്റ്റ് കാണാൻ അനുവദിക്കുക",
            "private_account" to "സ്വകാര്യ അക്കൗണ്ട്",
            "private_account_desc" to "കണക്ഷനുകൾക്ക് മാത്രമേ വിവരങ്ങൾ കാണാൻ കഴിയൂ",
            "blocked_list" to "ബ്ലੋക്ക് ചെയ്തവരുടെ പട്ടിക",
            "delete_account" to "അക്കൗണ്ട് ശാശ്വതമായി ഇല്ലാതാക്കുക",
            "app_data" to "ആപ്പും ഡാറ്റയും",
            "clear_cache" to "കാഷെ മായ്ക്കുക",
            "support_social" to "പിന്തുണയും സോഷ്യലും",
            "help_center" to "സഹായ കേന്ദ്രം / ഞങ്ങളെ ബന്ധപ്പെടുക",
            "report_bug" to "ബഗ് റിപ്പോർട്ട് ചെയ്യുക",
            "share_app" to "ആപ്പ് പങ്കിടുക",
            "rate_us" to "പ്ലേ സ്റ്റോറിൽ ഞങ്ങളെ റേറ്റുചെയ്യുക",
            "unverified" to "സ്ഥിരീകരിക്കാത്തത്",
            "verified_filter" to "സ്ഥിരീകരിച്ചത്",
            "blocked_filter" to "ബ്ലੋക്ക് ചെയ്തത്",
            "home" to "ഹോം",
            "tools" to "ടൂളുകൾ",
            "profile" to "പ്രൊഫൈൽ",
            "activity_logs" to "പ്രവർത്തന ലോഗുകൾ",
            "no_activity_logs" to "സമീപകാല പ്രവർത്തനങ്ങളൊന്നുമില്ല",
            "my_profile_title" to "എന്റെ പ്രൊഫഷണൽ പ്രൊഫൈൽ",
            "prof_details" to "പ്രൊഫഷണൽ വിവരങ്ങൾ",
            "lang_sep" to "ഭാഷ",
            "preview" to "പ്രിവ്യൂ",
            "service_area" to "സർവീസ് ഏരിയ",
            "save_all" to "എല്ലാ വിവരങ്ങളും സംരക്ഷിക്കുക",
            "saved_toast" to "സംരക്ഷിച്ചു",
            "live_map_desc" to "ലൈവ് മാപ്പ് - അടുത്തുള്ള വിദഗ്ധരെ കണ്ടെത്തുക",
            "loc_req" to "ലൊക്കേഷൻ അനുമതി ആവശ്യമാണ്",
            "loc_req_desc" to "അടുത്തുള്ളവരെ കാണാൻ അനുമതി നൽകുക",
            "grant_perm" to "അനുമതി നൽകുക",
            "prof_proximity" to "നിങ്ങളുടെ അടുത്തുള്ള പ്രൊഫഷണലുകൾ"
        ),
    )

    fun translate(key: String, language: AppLanguage): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }
}
