package com.example.ui.localization

import java.util.Locale

enum class AppLanguage(val code: String, val displayName: String) {
    ENGLISH("en", "English"),
    HINDI("hi", "हिन्दी (Hindi)"),
    BENGALI("bn", "বাংলা (Bengali)"),
    TAMIL("ta", "தமிழ் (Tamil)"),
    TELUGU("te", "తెలుగు (Telugu)"),
    ARABIC("ar", "العربية (Arabic)"),
    URDU("ur", "اردو (Urdu)"),
    MARATHI("mr", "मराठी (Marathi)"),
    GUJARATI("gu", "ગુજરાતી (Gujarati)"),
    PUNJABI("pa", "ਪੰਜਾਬੀ (Punjabi)"),
    MALAYALAM("ml", "മലയാളം (Malayalam)")
}

object JobaayaLocalization {
    
    fun detectDeviceLanguage(): AppLanguage {
        val defaultLang = Locale.getDefault().language
        return AppLanguage.entries.find { it.code == defaultLang } ?: AppLanguage.ENGLISH
    }

    private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_tagline" to "Professional Networking & Business Growth",
            "search_placeholder" to "Search profession, skill, location...",
            "near_me" to "Near Me",
            "chats" to "Chats",
            "notes" to "My Notes",
            "settings" to "Settings",
            "admin_panel" to "Admin Panel",
            "calculator" to "Calculator",
            "bookmarks" to "Bookmarks",
            "login_title" to "Welcome",
            "login_subtitle" to " ",
            "otp_login" to "OTP Mobile Login",
            "email_login" to "Email Login",
            "google_signin" to "Google Sign-In",
            "enter_mobile" to "Enter Mobile Number",
            "enter_otp" to "Enter 6-Digit OTP",
            "send_otp" to "Send Verification Code",
            "verify_otp" to "Verify & Proceed",
            "enter_email" to "Enter Email Address",
            "enter_password" to "Enter Password",
            "login" to "Login",
            "logout" to "Log Out",
            "register" to "Complete Registration",
            "select_account_type" to "Select Your Account Type",
            "customer" to "Customer",
            "professional" to "Professional",
            "business" to "Business",
            "full_name" to "Full Name",
            "profession" to "Profession (e.g. Electrician, Lawyer)",
            "skills" to "Skills (comma separated)",
            "mobile_number" to "Mobile Number",
            "email" to "Email Address",
            "address" to "Full Address / Location text",
            "experience" to "Years of Experience",
            "languages" to "Languages Spoken (comma separated)",
            "about" to "About / Working details (Free Text)",
            "save_profile" to "Save Professional Profile",
            "hire_me" to "Hire Me",
            "hire_now" to "Send Hiring Enquiry",
            "call" to "Call Now",
            "whatsapp" to "WhatsApp Chat",
            "profile_views" to "Profile Views",
            "interactions" to "Interactions",
            "reviews" to "Customer Reviews",
            "write_review" to "Write a Review",
            "submit_review" to "Submit Star Rating",
            "report" to "Report Profile",
            "block" to "Block User",
            "sp_block_success" to "User blocked successfully.",
            "sp_report_success" to "Profile reported to moderators.",
            "status_available" to "Available for Work",
            "status_busy" to "Currently Busy",
            "status_offline" to "Offline",
            "working_hours" to "Working Hours",
            "avail_title" to "My Work Availability",
            "notifications" to "Activity Alerts",
            "notification_settings" to "Push Notifications Toggle",
            "gps_locate" to "Enable Public GPS Sharing",
            "directions" to "Get Route Directions",
            "share_profile" to "Share Profile",
            "qr_share" to "Profile QR Code Scanner",
            "verified" to "Verified Professional",
            "badge" to "Grant Verification Badge",
            "admin_users" to "Accounts Manager",
            "admin_reports" to "Moderation Audit Logs",
            "admin_analytics" to "Growth Insights Dashboard",
            "create_note" to "Create Note",
            "note_title" to "Title",
            "note_body" to "Write something...",
            "delete" to "Delete",
            "calc_title" to "Service Calculator",
            "calc_hint" to "Calculate rates, & quotations",
            "currency_counter" to "Cash Counter",
            "hiring_success" to "Congratulation! Your hiring enquiry has been dispatched locally.",
            "unlimited_msg" to "Enter any custom trade. Supports electrician, mechanic, doctor, consultant, or any future profession.",
            "no_results" to "No professionals match your filters. Try search keywords!",
            "set_photo" to "Set Profile Photo",
            "adjust_photo" to "Adjust Photo",
            "save_photo" to "Save Photo",
            "cancel" to "Cancel",
            "zoom_to_fit" to "Zoom to Fit",
            "new_to_app" to "New to jobaaya?",
            "filters" to "Filters",
            "refine_search" to "Refine Network Search",
            "connect" to "Connect",
            "connected" to "Connected",
            "select_language" to "Select Language",
            "all" to "All",
            "total_amount" to "Total Amount",
            "privacy_settings" to "Privacy Settings",
            "public_mobile" to "Public Mobile Number",
            "public_mobile_desc" to "Allow everyone to see your contact",
            "private_account" to "Private Account",
            "private_account_desc" to "Only connections can view full details",
            "blocked_list" to "Blocked Users List",
            "delete_account" to "Delete Account Permanently",
            "app_data" to "App & Data",
            "clear_cache" to "Clear Cache",
            "support_social" to "Support & Social",
            "help_center" to "Help Center / Contact Us",
            "report_bug" to "Report a Bug",
            "share_app" to "Share jobaaya App",
            "rate_us" to "Rate Us on Play Store",
            "unverified" to "Unverified",
            "verified_filter" to "Verified",
            "blocked_filter" to "Blocked",
            "home" to "Home",
            "tools" to "Tools",
            "profile" to "Profile",
            "activity_logs" to "Platform Activity Logs",
            "no_activity_logs" to "No recent activity logs",
            "my_profile_title" to "MY PROFESSIONAL PROFILE",
            "prof_details" to "Professional Details",
            "lang_sep" to "Languages (comma separated)",
            "preview" to "Preview",
            "service_area" to "Service Area",
            "save_all" to "Save All Details",
            "saved_toast" to "Saved",
            "live_map_desc" to "Live Network Map - Find local experts nearby",
            "loc_req" to "Location Access Required",
            "loc_req_desc" to "Grant permission to see nearby tradespeople",
            "grant_perm" to "Grant Permission",
            "prof_proximity" to "Professionals in Your Proximity"
        ),
        AppLanguage.HINDI to mapOf(
            "app_tagline" to "पेशेवर नेटवर्किंग और व्यावसायिक विकास",
            "search_placeholder" to "पेशा, कौशल, या स्थान खोजें...",
            "near_me" to "मेरे पास",
            "chats" to "बातचीत",
            "notes" to "मेरी टिप्पणियाँ",
            "settings" to "सेटिंग्स",
            "admin_panel" to "एडमिन पैनल",
            "calculator" to "कैलकुलेटर",
            "bookmarks" to "बुकमार्क",
            "login_title" to "jobaaya में आपका स्वागत है",
            "login_subtitle" to "पेशेवर विकास और नेटवर्किंग मंच",
            "otp_login" to "ओटीपी मोबाइल लॉगिन",
            "email_login" to "ईमेल लॉगिन",
            "google_signin" to "गूगल साइन-इन",
            "enter_mobile" to "मोबाइल नंबर दर्ज करें",
            "enter_otp" to "6-अंकीय ओटीपी दर्ज करें",
            "send_otp" to "सत्यापन कोड भेजें",
            "verify_otp" to "सत्यापित करें और आगे बढ़ें",
            "enter_email" to "ईमेल पता दर्ज करें",
            "enter_password" to "पासवर्ड दर्ज करें",
            "login" to "लॉगिन करें",
            "logout" to "लॉग आउट",
            "register" to "पंजीकरण पूरा करें",
            "select_account_type" to "अपना खाता प्रकार चुनें",
            "customer" to "ग्राहक (Customer)",
            "professional" to "पेशेवर (Professional)",
            "business" to "व्यवसाय (Business)",
            "full_name" to "पूरा नाम",
            "profession" to "पेशा (जैसे प्लंबर, वकील, बिजली मिस्त्री)",
            "skills" to "कौशल (अल्पविराम से अलग)",
            "mobile_number" to "मोबाइल नंबर",
            "email" to "ईमेल पता",
            "address" to "पूरा पता / स्थान",
            "experience" to "अनुभव (वर्षों में)",
            "languages" to "बोली जाने वाली भाषाएं",
            "about" to "मेरे बारे में / काम का विवरण",
            "save_profile" to "प्रोफ़ाइल सहेजें",
            "hire_me" to "हायर करें (Hire)",
            "hire_now" to "पूछताछ भेजें",
            "call" to "कॉल करें",
            "whatsapp" to "व्हाट्सएप चैट",
            "profile_views" to "प्रोफ़ाइल व्यूज",
            "interactions" to "बातचीत / क्लिक",
            "reviews" to "ग्राहक समीक्षाएं",
            "write_review" to "समीक्षा लिखें",
            "submit_review" to "रेटिंग सबमिट करें",
            "report" to "रिपोर्ट करें",
            "block" to "ब्लॉक करें",
            "sp_block_success" to "उपयोगकर्ता को ब्लॉक कर दिया गया है।",
            "sp_report_success" to "प्रोफ़ाइल की रिपोर्ट एडमिन को की गई।",
            "status_available" to "काम के लिए उपलब्ध",
            "status_busy" to "अभी व्यस्त",
            "status_offline" to "ऑफ़लाइन",
            "working_hours" to "काम के घंटे",
            "avail_title" to "काम की उपलब्धता",
            "notifications" to "गतिविधि अलर्ट",
            "notification_settings" to "पुश नोटिफिकेशन सेटिंग्स",
            "gps_locate" to "सार्वजनिक जीपीएस स्थान दिखाना",
            "directions" to "मार्ग निर्देश",
            "share_profile" to "प्रोफ़ाइल साझा करें",
            "qr_share" to "प्रोफ़ाइल क्यूআর कोड",
            "verified" to "सत्यापित पेशेवर ⚡",
            "badge" to "सत्यापन बैज दें",
            "admin_users" to "खाता प्रबंधक",
            "admin_reports" to "रिपोर्ट और ब्लॉक ऑडिट",
            "admin_analytics" to "व्यावसायिक अंतर्दृष्टि",
            "create_note" to "क्रिएट नोट",
            "note_title" to "शीर्षक",
            "note_body" to "कुछ लिखें...",
            "delete" to "हटाएं",
            "calc_title" to "सेवा दर और कोटेशन कैलकुलेटर",
            "calc_hint" to "दर और कोटेशन की गणना करें",
            "currency_counter" to "キャッシュカウンター",
            "hiring_success" to "बधाई! आपकी पूछताछ स्थानीय स्तर पर भेज दी गई है।",
            "unlimited_msg" to "किसी भी पेशे को दर्ज करें। कोई प्रतिबंध नहीं है।",
            "no_results" to "कोई पेशेवर नहीं मिला। कृपया अन्य खोज शब्द आज़माएं।",
            "set_photo" to "प्रोफ़ाइल फोटो सेट करें",
            "adjust_photo" to "फोटो को सही करें",
            "save_photo" to "फोटो सहेजें",
            "cancel" to "रद्द करें",
            "zoom_to_fit" to "फिट करने के लिए ज़ूम करें",
            "new_to_app" to "jobaaya पर नए हैं?",
            "filters" to "फ़िल्टर",
            "refine_search" to "खोज को बेहतर बनाएं",
            "connect" to "जुड़ें",
            "connected" to "जुड़े हुए",
            "select_language" to "भाषा चुनें",
            "all" to "सभी",
            "total_amount" to "कुल राशि",
            "privacy_settings" to "गोपनीयता सेटिंग्स",
            "public_mobile" to "सार्वजनिक मोबाइल नंबर",
            "public_mobile_desc" to "सभी को अपना संपर्क देखने दें",
            "private_account" to "निजी खाता",
            "private_account_desc" to "केवल कनेक्शन ही पूर्ण विवरण देख सकते हैं",
            "blocked_list" to "ब्लॉक किए गए उपयोगकर्ताओं की सूची",
            "delete_account" to "स्थायी रूप से खाता हटाएं",
            "app_data" to "ऐप और डेटा",
            "clear_cache" to "कैश साफ करें",
            "support_social" to "सहायता और सोशल",
            "help_center" to "सहायता केंद्र / हमसे संपर्क करें",
            "report_bug" to "बग की रिपोर्ट करें",
            "share_app" to "jobaaya ऐप साझा करें",
            "rate_us" to "हमें प्ले स्टोर पर रेट करें",
            "unverified" to "असत्यापित",
            "verified_filter" to "सत्यापित",
            "blocked_filter" to "ब्लॉक किया गया",
            "home" to "होम",
            "tools" to "टूल्स",
            "profile" to "प्रोफाइल",
            "activity_logs" to "प्लेटफॉर्म गतिविधि लॉग",
            "no_activity_logs" to "कोई हालिया गतिविधि लॉग नहीं है",
            "my_profile_title" to "मेरी पेशेवर प्रोफ़ाइल",
            "prof_details" to "पेशेवर विवरण",
            "lang_sep" to "भाषाएं (अल्पविराम से अलग)",
            "preview" to "पूर्वावलोकन",
            "service_area" to "सेवा क्षेत्र",
            "save_all" to "सभी विवरण सहेजें",
            "saved_toast" to "सहेजा गया",
            "live_map_desc" to "लाइव नेटवर्क मैप - आस-पास के स्थानीय विशेषज्ञों को खोजें",
            "loc_req" to "स्थान की अनुमति आवश्यक है",
            "loc_req_desc" to "आस-पास के पेशेवरों को देखने के लिए अनुमति दें",
            "grant_perm" to "अनुमति दें",
            "prof_proximity" to "आपके पास के पेशेवर"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_tagline" to "পেশাদার নেটওয়ার্কিং এবং ব্যবসায়িক বৃদ্ধি",
            "search_placeholder" to "পেশা, দক্ষতা বা স্থান খুঁজুন...",
            "near_me" to "আমার কাছাকাছি",
            "chats" to "চ্যাট",
            "notes" to "আমার নোট",
            "settings" to "সেটিংস",
            "login" to "লগইন",
            "register" to "নিবন্ধন সম্পন্ন করুন",
            "hire_me" to "হায়ার করুন",
            "verified" to "যাচাইকৃত পেশাদার",
            "call" to "কল করুন",
            "whatsapp" to "হোয়াটসঅ্যাপ চ্যাট",
            "save_profile" to "প্রোফাইল সংরক্ষণ করুন"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_tagline" to "தொழில்முறை நெட்வொர்க்கிங் மற்றும் வணிக வளர்ச்சி",
            "search_placeholder" to "தொழில், திறன் அல்லது இடத்தைத் தேடுங்கள்...",
            "near_me" to "எனக்கு அருகில்",
            "chats" to "அரட்டைகள்",
            "notes" to "எனது குறிப்புகள்",
            "settings" to "அமைப்புகள்",
            "login" to "உள்நுழை",
            "register" to "பதிவை முடிக்கவும்",
            "hire_me" to "வேலைக்கு அமர்த்தவும்",
            "verified" to "சரிபார்க்கப்பட்ட நிபுணர்",
            "call" to "இப்போதே அழையுங்கள்",
            "whatsapp" to "வாட்ஸ்அப் அரட்டை",
            "save_profile" to "சுயவிவரத்தைச் சேமி"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_tagline" to "ప్రొఫెషనల్ నెట్‌వర్కింగ్ & వ్యాపార వృద్ధి",
            "search_placeholder" to "వృత్తి, నైపుణ్యం లేదా స్థానాన్ని వెతకండి...",
            "near_me" to "నా దగ్గరలో",
            "chats" to "చాట్‌లు",
            "notes" to "నా గమనికలు",
            "settings" to "సెట్టింగ్‌లు",
            "login" to "లాగిన్",
            "register" to "రిజిస్ట్రేషన్ పూర్తి చేయండి",
            "hire_me" to "హైర్ చేయండి",
            "verified" to "ధృవీకరించబడిన ప్రొఫెషనల్",
            "call" to "కాల్ చేయండి",
            "whatsapp" to "వాట్సాప్ చాట్",
            "save_profile" to "ప్రొఫైల్‌ను సేవ్ చేయండి"
        ),
        AppLanguage.ARABIC to mapOf(
            "app_tagline" to "التواصل المهني ونمو الأعمال",
            "search_placeholder" to "ابحث عن مهنة، مهارة، موقع...",
            "near_me" to "بالقرب مني",
            "chats" to "المحادثات",
            "notes" to "ملاحظاتي",
            "settings" to "الإعدادات",
            "admin_panel" to "لوحة الإدارة",
            "calculator" to "الحاسبة",
            "bookmarks" to "الإشارات المرجعية",
            "login_title" to "مرحباً بك",
            "login_subtitle" to "منصة التواصل المهني ونمو الأعمال",
            "otp_login" to "الدخول عبر رمز OTP",
            "email_login" to "الدخول عبر البريد الإلكتروني",
            "google_signin" to "تسجيل الدخول عبر جوجل",
            "enter_mobile" to "أدخل رقم الجوال",
            "enter_otp" to "أدخل رمز OTP المكون من 6 أرقام",
            "send_otp" to "إرسال رمز التحقق",
            "verify_otp" to "التحقق والمتابعة",
            "enter_email" to "أدخل البريد الإلكتروني",
            "enter_password" to "أدخل كلمة المرور",
            "login" to "تسجيل الدخول",
            "logout" to "تسجيل الخروج",
            "register" to "إكمال التسجيل",
            "select_account_type" to "اختر نوع حسابك",
            "customer" to "عميل",
            "professional" to "مهني",
            "business" to "عمل تجاري",
            "full_name" to "الاسم الكامل",
            "profession" to "المهنة (مثلاً كهربائي، محامٍ)",
            "skills" to "المهارات",
            "mobile_number" to "رقم الجوال",
            "email" to "البريد الإلكتروني",
            "address" to "العنوان الكامل / الموقع",
            "experience" to "الخبرة (بالسنوات)",
            "languages" to "اللغات التي تتحدثها",
            "about" to "عني / تفاصيل العمل",
            "save_profile" to "حفظ الملف الشخصي",
            "hire_me" to "وظفني",
            "hire_now" to "إرسال استفسار توظيف",
            "call" to "اتصل الآن",
            "whatsapp" to "دردشة واتساب",
            "profile_views" to "مشاهدات الملف الشخصي",
            "interactions" to "التفاعلات",
            "reviews" to "تقييمات العملاء",
            "write_review" to "اكتب تقييماً",
            "submit_review" to "إرسال التقييم",
            "report" to "إبلاغ",
            "block" to "حظر",
            "sp_block_success" to "تم حظر المستخدم بنجاح.",
            "sp_report_success" to "تم إبلاغ المشرفين عن الملف الشخصي.",
            "status_available" to "متاح للعمل",
            "status_busy" to "مشغول حالياً",
            "status_offline" to "غير متصل",
            "working_hours" to "ساعات العمل",
            "avail_title" to "توفري للعمل",
            "notifications" to "تنبيهات النشاط",
            "notification_settings" to "إعدادات الإشعارات",
            "gps_locate" to "تفعيل مشاركة الموقع العام",
            "directions" to "الاتجاهات",
            "share_profile" to "مشاركة الملف الشخصي",
            "qr_share" to "رمز QR للملف الشخصي",
            "verified" to "محترف موثق",
            "badge" to "منح شارة التوثيق",
            "admin_users" to "مدير الحسابات",
            "admin_reports" to "سجلات الرقابة",
            "admin_analytics" to "لوحة رؤى النمو",
            "create_note" to "إنشاء ملاحظة",
            "note_title" to "العنوان",
            "note_body" to "اكتب شيئاً...",
            "delete" to "حذف",
            "calc_title" to "حاسبة الخدمة",
            "calc_hint" to "حساب الأسعار والعروض",
            "currency_counter" to "عداد النقد",
            "hiring_success" to "مبروك! تم إرسال استفسار التوظيف الخاص بك.",
            "unlimited_msg" to "أدخل أي مهنة مخصصة. لا توجد قيود.",
            "no_results" to "لا يوجد محترفون يطابقون بحثك.",
            "set_photo" to "تعيين صورة الملف الشخصي",
            "adjust_photo" to "تعديل الصورة",
            "save_photo" to "حفظ الصورة",
            "cancel" to "إلغاء",
            "zoom_to_fit" to "تكبير للملائمة",
            "new_to_app" to "جديد في jobaaya؟",
            "filters" to "الفلاتر",
            "refine_search" to "تحسين البحث",
            "connect" to "اتصال",
            "connected" to "متصل",
            "select_language" to "اختر اللغة",
            "all" to "الكل",
            "total_amount" to "المبلغ الإجمالي",
            "privacy_settings" to "إعدادات الخصوصية",
            "public_mobile" to "رقم الجوال العام",
            "public_mobile_desc" to "السماح للجميع برؤية جهة الاتصال الخاصة بك",
            "private_account" to "حساب خاص",
            "private_account_desc" to "فقط جهات الاتصال يمكنها رؤية التفاصيل الكاملة",
            "blocked_list" to "قائمة المستخدمين المحظورين",
            "delete_account" to "حذف الحساب نهائياً",
            "app_data" to "التطبيق والبيانات",
            "clear_cache" to "مسح ذاكرة التخزين المؤقت",
            "support_social" to "الدعم والتواصل",
            "help_center" to "مركز المساعدة / اتصل بنا",
            "report_bug" to "الإبلاغ عن خلل",
            "share_app" to "مشاركة تطبيق jobaaya",
            "rate_us" to "قيمنا على المتجر",
            "unverified" to "غير موثق",
            "verified_filter" to "موثق",
            "blocked_filter" to "محظور",
            "home" to "الرئيسية",
            "tools" to "الأدوات",
            "profile" to "الملف الشخصي",
            "activity_logs" to "سجلات نشاط المنصة",
            "no_activity_logs" to "لا توجد سجلات نشاط حديثة",
            "my_profile_title" to "ملفي الشخصي المهني",
            "prof_details" to "التفاصيل المهنية",
            "lang_sep" to "اللغات",
            "preview" to "معاينة",
            "service_area" to "منطقة الخدمة",
            "save_all" to "حفظ جميع التفاصيل",
            "saved_toast" to "تم الحفظ",
            "live_map_desc" to "خريطة الشبكة الحية - ابحث عن خبراء محليين",
            "loc_req" to "مطلوب الوصول إلى الموقع",
            "loc_req_desc" to "امنح الإذن لرؤية المهنيين القريبين",
            "grant_perm" to "منح الإذن",
            "prof_proximity" to "المحترفون القريبون منك"
        ),
        AppLanguage.URDU to mapOf(
            "app_tagline" to "پیشہ ورانہ نیٹ ورکنگ اور کاروباری ترقی",
            "search_placeholder" to "پیشہ، مہارت یا جگہ تلاش کریں...",
            "near_me" to "میرے قریب",
            "chats" to "بات چیت",
            "notes" to "میرے نوٹس",
            "settings" to "ترتیبات",
            "admin_panel" to "ایڈمن پینل",
            "calculator" to "کیلکولیٹر",
            "bookmarks" to "بک مارکس",
            "login_title" to "خوش آمدید",
            "login_subtitle" to "پیشہ ورانہ ترقی اور نیٹ ورکنگ پلیٹ فارم",
            "otp_login" to "او ٹی پی موبائل لاگ ان",
            "email_login" to "ای میل لاگ ان",
            "google_signin" to "گوگل سائن ان",
            "enter_mobile" to "موبائل نمبر درج کریں",
            "enter_otp" to "6 ہندسوں کا او ٹی پی درج کریں",
            "send_otp" to "تصدیقی کوڈ بھیجیں",
            "verify_otp" to "تصدیق کریں اور آگے بڑھیں",
            "enter_email" to "ای میل ایڈریس درج کریں",
            "enter_password" to "پاس ورڈ درج کریں",
            "login" to "لاگ ان",
            "logout" to "لاگ آؤٹ",
            "register" to "رجسٹریشن مکمل کریں",
            "select_account_type" to "اپنے اکاؤنٹ کی قسم منتخب کریں",
            "customer" to "صارف",
            "professional" to "پیشہ ور",
            "business" to "کاروبار",
            "full_name" to "پورا نام",
            "profession" to "پیشہ (مثلاً الیکٹریشن، وکیل)",
            "skills" to "مہارتیں",
            "mobile_number" to "موبائل نمبر",
            "email" to "ای میل ایڈریس",
            "address" to "پورا پتہ / مقام",
            "experience" to "تجربہ (سالوں میں)",
            "languages" to "بولی جانے والی زبانیں",
            "about" to "میرے بارے میں / کام کی تفصیلات",
            "save_profile" to "پروفائل محفوظ کریں",
            "hire_me" to "ہائر کریں",
            "hire_now" to "پوچھ گچھ بھیجیں",
            "call" to "کال کریں",
            "whatsapp" to "واٹس ایپ چیٹ",
            "profile_views" to "پروفائل ویوز",
            "interactions" to "تعاملات",
            "reviews" to "صارفین کے جائزے",
            "write_review" to "جائزہ لکھیں",
            "submit_review" to "درجہ بندی جمع کریں",
            "report" to "رپورٹ کریں",
            "block" to "بلاک کریں",
            "sp_block_success" to "صارف کو کامیابی سے بلاک کر دیا گیا۔",
            "sp_report_success" to "پروفائل کی رپورٹ ماڈریٹرز کو کر دی گئی۔",
            "status_available" to "کام کے لیے دستیاب",
            "status_busy" to "ابھی مصروف ہے",
            "status_offline" to "آف لائن",
            "working_hours" to "کام کے اوقات",
            "avail_title" to "میری دستیابی",
            "notifications" to "سرگرمی کے الرٹس",
            "notification_settings" to "اطلاعات کی ترتیبات",
            "gps_locate" to "عوامی GPS شیئرنگ فعال کریں",
            "directions" to "راستہ دکھائیں",
            "share_profile" to "پروفائل شیئر کریں",
            "qr_share" to "پروفائل QR کوڈ",
            "verified" to "تصدیق شدہ پیشہ ور",
            "badge" to "تصدیق شدہ بیج دیں",
            "admin_users" to "اکاؤنٹ مینیجر",
            "admin_reports" to "رپورٹ اور بلاک آڈٹ",
            "admin_analytics" to "کاروباری بصیرت",
            "create_note" to "نوٹ بنائیں",
            "note_title" to "عنوان",
            "note_body" to "کچھ لکھیں...",
            "delete" to "حذف کریں",
            "calc_title" to "سروس ریٹ کیلکولیٹر",
            "calc_hint" to "ریٹ اور کوٹیشن کا حساب لگائیں",
            "currency_counter" to "کیش کاؤنٹر",
            "hiring_success" to "مبارک ہو! آپ کی پوچھ گچھ بھیج دی گئی ہے۔",
            "unlimited_msg" to "کسی بھی پیشے کو درج کریں۔ کوئی پابندی نہیں ہے۔",
            "no_results" to "کوئی پیشہ ور نہیں ملا۔ براہ کرم تلاش کے الفاظ تبدیل کریں۔",
            "set_photo" to "پروفائل فوٹو لگائیں",
            "adjust_photo" to "فوٹو درست کریں",
            "save_photo" to "فوٹو محفوظ کریں",
            "cancel" to "منسوخ کریں",
            "zoom_to_fit" to "فٹ کرنے کے لیے زوم کریں",
            "new_to_app" to "ایپ پر نئے ہیں؟",
            "filters" to "فلٹرز",
            "refine_search" to "تلاش کو بہتر بنائیں",
            "connect" to "جڑیں",
            "connected" to "جڑے ہوئے",
            "select_language" to "زبان منتخب کریں",
            "all" to "تمام",
            "total_amount" to "کل رقم",
            "privacy_settings" to "رازداری کی ترتیبات",
            "public_mobile" to "عوامی موبائل نمبر",
            "public_mobile_desc" to "ہر کسی کو اپنا رابطہ دیکھنے کی اجازت دیں",
            "private_account" to "نجی اکاؤنٹ",
            "private_account_desc" to "صرف جڑے ہوئے افراد مکمل تفصیلات دیکھ سکتے ہیں",
            "blocked_list" to "بلاک شدہ صارفین کی فہرست",
            "delete_account" to "اکاؤنٹ مستقل طور پر حذف کریں",
            "app_data" to "ایپ اور ڈیٹا",
            "clear_cache" to "کیشے صاف کریں",
            "support_social" to "سپورٹ اور سوشل",
            "help_center" to "سپورٹ سینٹر / ہم سے رابطہ کریں",
            "report_bug" to "بگ رپورٹ کریں",
            "share_app" to "ایپ شیئر کریں",
            "rate_us" to "ہمیں ریٹ کریں",
            "unverified" to "غیر تصدیق شدہ",
            "verified_filter" to "تصدیق شدہ",
            "blocked_filter" to "بلاک شدہ",
            "home" to "ہوم",
            "tools" to "ٹولز",
            "profile" to "پروفائل",
            "activity_logs" to "سرگرمی لاگز",
            "no_activity_logs" to "کوئی حالیہ سرگرمی نہیں ہے",
            "my_profile_title" to "میری پیشہ ورانہ پروفائل",
            "prof_details" to "پیشہ ورانہ تفصیلات",
            "lang_sep" to "زبانیں",
            "preview" to "پیش نظارہ",
            "service_area" to "سروس ایریا",
            "save_all" to "تمام تفصیلات محفوظ کریں",
            "saved_toast" to "محفوظ کر لیا گیا",
            "live_map_desc" to "لائیو میپ - قریبی ماہرین تلاش کریں",
            "loc_req" to "مقام تک رسائی درکار ہے",
            "loc_req_desc" to "قریبی لوگوں کو دیکھنے کے لیے اجازت دیں",
            "grant_perm" to "اجازت دیں",
            "prof_proximity" to "آپ کے قریب پیشہ ور"
        ),
        AppLanguage.MARATHI to mapOf(
            "app_tagline" to "व्यावसायिक नेटवर्किंग आणि व्यवसाय वाढ",
            "search_placeholder" to "व्यवसाय, कौशल्य किंवा ठिकाण शोधा...",
            "near_me" to "माझ्या जवळ",
            "chats" to "चॅट्स",
            "notes" to "माझ्या नोट्स",
            "settings" to "सेटिंग्ज",
            "login" to "লগইন",
            "register" to "नोंदणी पूर्ण करा",
            "hire_me" to "हायर करा",
            "verified" to "सत्यापित व्यावसायिक",
            "call" to "कॉल करा",
            "whatsapp" to "व्हॉट्सॲप चॅट",
            "save_profile" to "प्रोफाइल जतन करा"
        ),
        AppLanguage.GUJARATI to mapOf(
            "app_tagline" to "વ્યાવસાયિક નેટવર્કિંગ અને વ્યવસાય વૃદ્ધિ",
            "search_placeholder" to "વ્યવસાય, કૌશલ્ય અથવા સ્થળ શોધો...",
            "near_me" to "મારી નજીક",
            "chats" to "ચેટ્સ",
            "notes" to "મારી નોંધો",
            "settings" to "સેટિંગ્સ",
            "login" to "લોગિન",
            "register" to "નોંધણી પૂર્ણ કરો",
            "hire_me" to "હાયર કરો",
            "verified" to "ચકાસાયેલ વ્યાવસાયિક",
            "call" to "કોલ કરો",
            "whatsapp" to "વોટ્સએપ ચેટ",
            "save_profile" to "પ્રોફાઇલ સાચવો"
        ),
        AppLanguage.PUNJABI to mapOf(
            "app_tagline" to "ਪੇਸ਼ੇਵਰ ਨੈੱਟਵਰਕਿੰਗ ਅਤੇ ਕਾਰੋਬਾਰੀ ਵਿਕਾਸ",
            "search_placeholder" to "ਪੇਸ਼ਾ, ਹੁਨਰ ਜਾਂ ਸਥਾਨ ਲੱਭੋ...",
            "near_me" to "ਮੇਰੇ ਨੇੜੇ",
            "chats" to "ਚੈਟਸ",
            "notes" to "ਮੇਰੇ ਨੋਟਸ",
            "settings" to "ਸੈਟਿੰਗਾਂ",
            "login" to "ਲੌਗਇਨ",
            "register" to "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰੋ",
            "hire_me" to "ਹਾਇਰ ਕਰੋ",
            "verified" to "ਤਸਦੀਕ ਪੇਸ਼ੇਵਰ",
            "call" to "ਕਾਲ ਕਰੋ",
            "whatsapp" to "ਵਟਸਐਪ ਚੈਟ",
            "save_profile" to "ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਕਰੋ"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_tagline" to "പ്രൊഫഷണൽ നെറ്റ്വർക്കിംഗും ബിസിനസ്സ് വളർച്ചയും",
            "search_placeholder" to "തൊഴിൽ, വൈദഗ്ധ്യം അല്ലെങ്കിൽ സ്ഥലം തിരയുക...",
            "near_me" to "എന്റെ അടുത്ത്",
            "chats" to "ചാറ്റുകൾ",
            "notes" to "എന്റെ കുറിപ്പുകൾ",
            "settings" to "ക്രമീകരണങ്ങൾ",
            "login" to "ലോഗിൻ",
            "register" to "രജിസ്ട്രേഷൻ പൂർത്തിയാക്കുക",
            "hire_me" to "ഹയർ ചെയ്യുക",
            "verified" to "സ്ഥിരീകരിച്ച പ്രൊഫഷണൽ",
            "call" to "ഇപ്പോൾ വിളിക്കുക",
            "whatsapp" to "വാട്ട്‌സ്ആപ്പ് ചാറ്റ്",
            "save_profile" to "പ്രൊഫൈൽ സംരക്ഷിക്കുക"
        )
    )

    fun translate(key: String, language: AppLanguage): String {
        return translations[language]?.get(key)
            ?: translations[AppLanguage.ENGLISH]?.get(key)
            ?: key
    }
}
